### ISSUE TITLE
First character is replaced with a slash

### ISSUE THREAD

**Issue by michaelpwilson** [systemjs/systemjs#1611] opened 2017-03-07 11:34 UTC
I am using the latest version of System.js for when I'm developing my Angular 2 app.

The error I am receiving is:

    GET http://localhost:3000//odules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js 404 (Not Found)

The reason the 404 is happening is because a slash is replacing the first character.

Here is my system.config.js:

    (function (global) {
      System.config({
        paths: {
          'npm:': './modules/'
        },
        map: {
          app: '',
          '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
          '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
          '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
          '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
          '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
          '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
          '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
          '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
          'rxjs': 'npm:rxjs'
        },
        packages: {
          app: {
            main: './dist/app/main.js',
            defaultExtension: 'js'
          },
          rxjs: {
            defaultExtension: 'js'
          }
        }
      });
    })(this);

I can't understand where I am going wrong here? Everything was working fine until I updated my dependencies.

    {
       "dependencies": {
          "@angular/common": "~2.4.9",
          "@angular/compiler": "~2.4.9",
          "@angular/core": "~2.4.9",
          "@angular/forms": "~2.4.9",
          "@angular/http": "~2.4.9",
          "@angular/platform-browser": "~2.4.9",
          "@angular/platform-browser-dynamic": "~2.4.9",
          "@angular/router": "~3.4.9",
          "core-js": "^2.4.1",
          "rxjs": "5.2.0",
          "systemjs": "0.20.9",
          "zone.js": "^0.7.7"
       },
       "devDependencies": {
          "browser-sync": "^2.18.8",
          "ts-loader": "^2.0.1",
          "typescript": "^2.2.1",
          "webpack": "^2.2.1"
       }
    }

**Comment by guybedford** [comment] 2017-03-09 13:18
This looks like a duplicate of https://github.com/systemjs/systemjs/issues/1609.

**Closed** 2017-04-23 16:09 UTC
