### ISSUE TITLE
relative imports should be relative

### ISSUE THREAD

**Issue by jhoguet** [systemjs/systemjs#539] opened 2015-06-20 13:53 UTC
I have the following setup

I have a `/public` folder which contains `jspm_packages` etc. 

And I have a `/public/test` folder which contains `index.html`
```html
    <script src="../jspm_packages/system.js"></script>
    <script src="../config.js"></script>
    <script>
        // we have to set the base url so that it can resolve jspm_packages
        System.config({baseURL : '../'});
        // since the base url is set, we are no longer relative to ourselves and must walk into our folder
        System.import('./test/index');
    </script>
```

And I have a `public/test/index.js` and a `public/index.js` file. The content doesn't matter - the concern is over which file is requested. 

I understand why I need 
```js
        System.config({baseURL : '../'});
```
> so I can resolve `require('some-package')` to `../jspm_packages/` and not `test/jspm_packages` which does not exist. 

But I **expected** to be able to use 
```js
        System.import('./index');
```
to get the index.js file in my current folder. If I wanted the one from the parent folder I would do `System.import('../index')`

What is **actually** happening is `System.import('./index')` assumes it is relative to the baseURL and so I have to use `System.import('./test/index')`

I would expect a relative path to be relative to my current location. 

thoughts?

**Comment by guybedford** [comment] 2015-06-20 18:14
Which version of SystemJS are you using here? In the latest SystemJS your expected behaviour is what should happen by design.

**Comment by jhoguet** [comment] 2015-06-20 21:25
v0.16.11

```sh
npm install -g jspm
rm -rf jspm_packages
jspm install
```

Guessing I need to install the beta?

    npm install -g jspm@beta

**Comment by guybedford** [comment] 2015-06-21 13:07
Yes exactly.

**Comment by guybedford** [comment] 2015-06-22 19:15
Closing, but let me know if you have any further questions at all.

**Closed by guybedford** 2015-06-22 19:15 UTC

**Comment by smcmurray** [comment] 2015-08-13 16:47
In v0.18.6, System.import('./subdir/module.js') tries to import relative to baseURL instead of relative to the directory containing the script with the import.

**Comment by guybedford** [comment] 2015-08-13 17:24
@smcmurray to do a dynamic relative import use `System.import('./subdir/module.js', __moduleName)`. This use case will be handled by the spec in future, but `__moduleName` is our stopgap for now.

**Comment by smcmurray** [comment] 2015-08-13 17:41
__moduleName is not defined.

**Comment by guybedford** [comment] 2015-08-13 17:45
@smcmurray `__moduleName` is only defined for ES modules in SystemJS. So the code doing the `System.import` would need to itself be inside an ES module that has `export` or `import` syntax.

**Comment by smcmurray** [comment] 2015-08-14 20:01
So I'm not clear how to import a module resource in a non-ES6 module.

When a module includes css, or html, or additional js files, how do you import those?

**Comment by laurelnaiad** [comment] 2016-01-22 05:11
I've found that I cannot induce __moduleName to be defined by setting format to 'esm', but I can induce __dirname to be defined by setting format to 'cjs'... and that __dirname gives the path relative to the server root, which is just what I needed.
