### ISSUE TITLE
can't get value under webpack@5 dev-server

### ISSUE THREAD

**Issue by EastblueOkay** [systemjs/systemjs#2333] opened 2021-05-31 07:45 UTC
- SystemJS Version: 
- Which library are you using?
  - [x] system.js 
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [x] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?
no

### Question
System.import umd-bundler with webpack5 dev-server cannot get the value, but working well at webpack4.
I noticed that webpack5  exported value have no `__esModule` field.

### Repo
This problem can be reproduced in this repo:  
https://github.com/EastblueOkay/systemjs-issue-webpack5-umd

use `yarn add webpack@4` to  switch webpack4

**Comment by joeldenning** [comment] 2021-06-01 22:11
Thanks for providing the demonstration. This appears to be a bug in webpack. Below is part of the main.js bundle created by webpack (I added `devtool: 'source-map'` to the webpack config, but then turned off source maps in browser devtools, to see this easier):

```js
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be in strict mode.
(() => {
"use strict";
var __webpack_exports__ = {};
/*!******************!*\
  !*** ./index.js ***!
  \******************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "test": () => (/* binding */ test)
/* harmony export */ });
const test = () => {}
})();
```

Notice how there are two `__webpack_exports__` variables, but the one with the `test` export is inside of an IIFE and is modifying a function-local variable rather than the outer `__webpack_exports__` variable.

A related webpack bug appears to have been reported in https://github.com/webpack/webpack/issues/13165 and fixed in https://github.com/webpack/webpack/pull/13175. That fix was released in https://github.com/webpack/webpack/releases/tag/v5.35.1, but doesn't appear to have fully fixed the problem.

I'd suggest opening an issue with webpack for this, as this appears just to be a regression bug in webpack. Closing the issue here since it's not something systemjs can fix.

**Closed by joeldenning** 2021-06-01 22:11 UTC

**Comment by jogelin** [comment] 2021-12-11 18:41
@joeldenning I have a similar bug when importing rxjs with systemJs.

In fact, I am sharing the `rxjs` using systems. I am using the `umd` format and I get this error when it is loaded by `systemJs`:

![image](https://user-images.githubusercontent.com/954509/145687844-1778ce4d-0c88-40d8-ad3e-6afd29a5ec53.png)

![image](https://user-images.githubusercontent.com/954509/145687872-d8dcd74f-d0d7-4deb-99c7-8fac4ab3440e.png)

Below are some configurations to give more details:

`index.html`
```
...
    <script src="assets/node_modules/systemjs/dist/system.min.js"></script>
    <script src="assets/node_modules/systemjs/dist/extras/amd.min.js"></script>
    <script src="assets/node_modules/systemjs/dist/extras/named-exports.min.js"></script>
    <script src="assets/node_modules/systemjs/dist/extras/named-register.min.js"></script>

    <script type="systemjs-importmap">
      {
        "imports": {
          "single-spa": "/Portal/ES/assets/node_modules/single-spa/lib/system/single-spa.min.js",
          "rxjs": "/Portal/ES/assets/node_modules/rxjs/dist/bundles/rxjs.umd.min.js",
...
        }
      }
    </script>
...
```

`webpack.config.js`
```
...
    externals: [
      {
        'zone.js': 'zone.js',
        rxjs: 'rxjs', // if I remove this line, it works well because not shared anymore
...
```

`package.json`
```
...
"systemjs": "^6.11.0",
"rxjs": "~7.4.0",
...
```

**Comment by joeldenning** [comment] 2022-01-21 22:36
I haven't looked into this. Like I mentioned in my previous comment, the appropriate place to report this bug is webpack.

**Comment by jogelin** [comment] 2022-02-21 07:59
Just for info in case, someone has the same issue:

It was caused by the split chunk optimization in my case. I fixed it by making sure that my `webpack.config` is setting:
```
 optimization: {
      runtimeChunk: false,
      splitChunks: false,
    },
```
