### ISSUE TITLE
systemjs-transform-babel will transform AMD module

### ISSUE THREAD

**Issue by pigcan** [systemjs/systemjs#1972] opened 2019-07-23 11:53 UTC
```js
define(['./esm.js'], function (esm) {
  return esm;
});
```
===>

```js
System.register([], function (_export, _context) {
  "use strict";

  return {
    setters: [],
    execute: function () {
      //Calling define with module ID, dependency array, and factory function
      define(['./esm.js'], function (esm) {
        return esm;
      });
    }
  };
});
```

`esm.js` would not be loaded.

**Comment by joeldenning** [comment] 2019-07-23 15:29
I believe that this is intended behavior -- systemjs-transform-babel will turn ES modules into System.register format, but will not do so for other module formats. See [this line of code](https://github.com/systemjs/systemjs-transform-babel/blob/master/src/babel-transform.js#L8) and [@babel/plugin-transform-modules-systemjs](https://babeljs.io/docs/en/babel-plugin-transform-modules-systemjs), which only work on ES modules.

Converting AMD to System.register format would require using a new babel plugin. Perhaps https://github.com/systemjs/babel-plugin-transform-amd-system-dependencies or https://github.com/systemjs/babel-plugin-transform-amd-system-wrapper were intended to do this? Although they both seem old and unmaintained.

Closing this since I don't believe it's a bug. Feel free to comment further with more discussion or with a proposal to change systemjs-transform-babel.

**Closed by joeldenning** 2019-07-23 15:29 UTC

**Comment by pigcan** [comment] 2019-07-23 15:42
@joeldenning Thans for your reply.
As you said 

> systemjs-transform-babel will turn ES modules into System.register format, but will not do so for other module formats. 


But `systemjs-transform-babel` turn amd format module into System.register, it's an unexpected behavior.

**Comment by joeldenning** [comment] 2019-07-23 15:45
@pigcan -- systemjs-transform-babel relies entirely on `@babel/plugin-transform-modules-systemjs` to do the module conversion. That babel plugin interprets *all* code as if it were an ES module -- even your code that is not an ES module. So the plugin thinks your code is an ES module that just doesn't import or export anything.

See [this babel repl example](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=CYUwZglgdiAUDaByAdAehAZwLbIFYcQF0AaAAjAFcoBjAFwgHspTZMsBKUgbwChTSATiFoUBzNgG4eAX3YSgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.5.5&externalPlugins=%40babel%2Fplugin-transform-modules-systemjs%407.5.0) which shows you that the behavior that you are seeing is expected behavior for `@babel/plugin-transform-modules-systemjs`

**Comment by pigcan** [comment] 2019-07-23 16:53
Yes. I understood. I'm not doubt about the behavior of `@babel/plugin-transform-modules-systemjs`. I just confuse about `systemjs-transform-babel`.  
Anyway, I think maybe we need to develop a module to detect module format then keep it in the context, and `systemjs-transform-babel` expose a method or configure for helping us to determine the transform behavior.

**Comment by guybedford** [comment] 2019-07-23 22:36
This is effectively a configuration problem - being able to specify which files should go through the plugin and which shouldn't, which used to be what the `SystemJS` `meta` config was used for. In the latest SystemJS, there is still uncertainty over what patterns to use for configuration, and the hope was to have some discussion around this in https://github.com/systemjs/systemjs-transform-babel/issues/2. I'm open to contributions there.
