### ISSUE TITLE
jquery loading issue

### ISSUE THREAD

**Issue by theurere2** [systemjs/systemjs#2203] opened 2020-07-13 17:27 UTC
I am having difficulties with the loading of jquery for a dependency `jquery.mmenu`. At times jquery is loaded on time and at other times not when refreshing the page quickly. Here is my setup:
**package.json**
```json
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server",
    "build": "tsc"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "jquery": "^3.5.1",
    "jquery.mmenu": "^6.1.8",
    "lodash": "^4.17.15",
    "systemjs": "^6.3.3"
  },
  "devDependencies": {
    "typescript": "^3.9.6",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0"
  }
}
```
**html**
```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Try out systemjs</title>
	<script type="systemjs-importmap">
		{
			"imports": {
				"jquery": "./node_modules/jquery/dist/jquery.js",
				"lodash": "./node_modules/lodash/lodash.js",
				"mmenu": "./node_modules/jquery.mmenu/dist/jquery.mmenu.all.js",
				"main": "./dist/main.js"
			}
		}
	</script>
	<script type="systemjs-module" src="import:main"></script>
	<script type="text/javascript" src="node_modules/systemjs/dist/system.js"></script>
	<script type="text/javascript" src="node_modules/systemjs/dist/extras/named-exports.js"></script>
</head>
<body>
	<h1>Testing systemjs</h1>
</body>
</html>
```
**typescript main.ts**
```typescript

import jquery from 'jquery';
import mmenu from 'mmenu';

console.log('jquery', jquery);
console.log('mmenu', mmenu);
```
**compiled javascript main.js**
```javascript
System.register(["jquery", "mmenu"], function (exports_1, context_1) {
    "use strict";
    var jquery_1, mmenu_1;
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [
            function (jquery_1_1) {
                jquery_1 = jquery_1_1;
            },
            function (mmenu_1_1) {
                mmenu_1 = mmenu_1_1;
            }
        ],
        execute: function () {
            console.log('jquery', jquery_1.default);
            console.log('mmenu', mmenu_1.default);
        }
    };
});
```
**tsconfig.json**
```json
{
  "compilerOptions": {
    "outDir": "dist",
    "sourceMap": true,
    "target": "es2015",
    "module": "system",
    "lib": ["es2015", "dom"]
  }
}
```

**Comment by joeldenning** [comment] 2020-07-13 17:38
> At times jquery is loaded on time and at other times not when refreshing the page quickly

That doesn't sound good! Could you provide a code sandbox that demonstrates the issue? Here is a template that you can use: https://codesandbox.io/s/quirky-antonelli-2kusz?file=/index.html.

It likely is easiest just to paste the compiled output of main.js into a file in code sandbox, instead of trying to get your exact webpack/typescript configuration working in code sandbox.

**Comment by theurere2** [comment] 2020-07-14 07:32
Here is the code: https://codesandbox.io/s/weathered-cloud-2ywg9?file=/index.html. You have to open the browser console to see it - the error `TypeError: e is undefined` comes when quickly refreshing the browser reload button. In the app console nothing is displayed when the browser error comes.

**Comment by joeldenning** [comment] 2020-07-14 18:00
Thanks for the sandbox - I'm able to consistently reproduce the issue in that first sandbox.

Here is why it is not working when you omit the AMD extra:

1. `<script type="systemjs-module" src="import:main"></script>` causes `main.js` to be downloaded.
1. `main.js` specifies two dependencies - `System.register(["jquery", "mmenu"], ...`
1. SystemJS begins downloading both modules simultaneously. It loads and executes modules in parallel, without ensuring execution order. But it does ensure **instantiation** order (the `execute` function in a systemjs module).
1. jquery and mmenu are in UMD format. This means that they can work either as global variables or as AMD modules. Since you're not using the AMD extra, they are loaded via the [global loading](https://github.com/systemjs/systemjs/blob/master/dist/extras/global.js) extra, which is included in system.js.
1. Global modules do not separate loading/execution from instantiation. They do both in the same tick of the event loop. Additionally, they have no way of "waiting" for a dependency to be available - they just assume that any dependencies were loaded previously and are available on the `window` object.
1. Because of these limitations of global modules, there is a race condition between jquery and jquerymenu. If jquery loads first, then everything works. Otherwise, jquerymenu throws an error because it attempts to use a `window.jQuery` variable that doesn't exist.

Using the AMD extra solves the issue because AMD does separate loading/execution from instantiation. It also has a way of waiting for dependencies before instantiating. I would recommend using the AMD extra for this case, and am closing this issue as there is no bug here with SystemJS. Feel free to comment further or reopen.

**Closed by joeldenning** 2020-07-14 18:00 UTC
