### ISSUE TITLE
firefox dev tools not showing js files loaded by systemjs

### ISSUE THREAD

**Issue by yoavniran** [systemjs/systemjs#820] opened 2015-10-05 11:56 UTC
I've been working on a project and up until now blissfully using Chrome dev tools and was able to easily debug the JS files SystemJS loads asynchronously in dev time (not bundled).

this is the source tree in Chrome for my project: 

![20151005_144332-screenshot](https://cloud.githubusercontent.com/assets/1102278/10279632/ede18bec-6b6f-11e5-9b89-82595db094a2.png)

I encountered a strange JS issue and wanted to see whether theres a difference in how FF behaves. So opened FF and tried my test page. However, in the "Debugger" pane, I only see my html page, system.src.js and my config.js.
none of the many JS files appear. as you can see:

![20151005_144356-screenshot](https://cloud.githubusercontent.com/assets/1102278/10279699/6fbf6fd0-6b70-11e5-938c-44eeb3845026.png)

Firebug isnt much better either. At some point FireBug 2.0.2 showed the files but wasnt able to place a breakpoint (got only spinning thingie where i clicked).  Tried FireBug 3 (alpha) and it wasnt showing the files at all (like the FF debugger, which it seems to be using now).

Microsoft Edge was able to show all the files (although painfully in a flat list) and even able to place a breakpoint. But its a punishment to debug JS in IE/Edge 

I couldnt find any info about this anywhere. Has anyone also encountered this? Any solution?

I suppose I can debug in FF after bundling the code but would be nice to be able to use it with the files open.

thanks,
Yoav

**Comment by guybedford** [comment] 2015-10-05 12:16
We use a data URI sourceMappingURL along with sourceURL to provide in-browser debugging. Firefox and older IE have limited support for this feature. It would likely be most beneficial to follow this up at the appropriate browser bug tracker.

**Comment by yoavniran** [comment] 2015-10-06 07:48
yeah, was pretty much expecting this answer...
Wondering if someone can share from their experience/tips when troubleshooting code in non-chrome dev tools (that are so terribly handicapped) ?

**Comment by guybedford** [comment] 2015-10-07 16:18
Marking as a duplicate of https://github.com/systemjs/systemjs/issues/450, and making that one more general!

**Comment by guybedford** [comment] 2015-10-07 16:18
Individual browser bug tracking is very much appreciated on these.

**Closed by guybedford** 2015-10-07 16:18 UTC

**Comment by jdanyow** [comment] 2015-11-28 06:31
Here's the issue in BugZilla, FireFox's issue tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1224078
