### ISSUE TITLE
Why is the resource loaded from disk instead of there being a request (with either a 200 or 304 response)?

### ISSUE THREAD

**Issue by gjhommersom** [systemjs/systemjs#2302] opened 2021-02-17 15:22 UTC
- SystemJS Version: 6.8.3
- Which library are you using?
  - [x] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [x] AMD extra
  - [x] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?
No

### Question
We are using Single-SPA and when an application is loaded the response is 200 (disk cache/memory cache). Only opening the developer tools and checking `disable cache` a new version is fetched. 

However, when the resource is required through the browser directly it will return either a 200 with new content or a 304.

I found https://github.com/single-spa/single-spa/issues/369 on Single-SPA that points to https://github.com/systemjs/systemjs/issues/2070 that indicates a 304 should happen. 

Why is the resource loaded from disk instead of there being a request (with either a 200 or 304 response)?

**Comment by joeldenning** [comment] 2021-02-18 05:00
This is HTTP caching implemented by the browser. Here are some articles that may help:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#controlling_caching

If you want the browser to always request a new version, you should either change the name of the file or send a Cache-Control header with a low `max-age`, which will cause the browser to only cache it for a short time.

Closing this as the behavior is unrelated to systemjs/single-spa and is just part of how browser caches work. Feel free to comment further with additional questions.

**Closed by joeldenning** 2021-02-18 05:00 UTC

**Comment by gjhommersom** [comment] 2021-02-18 07:46
I want it to request a new version when it has changed. To my knowledge the ETag should assist with that. And as I mentioned before, it does work as expected when directly accessing the resource.

SystemJS import: 
![image](https://user-images.githubusercontent.com/28047460/108312726-7ae95d00-71b7-11eb-92c1-7145e60de1b1.png)

Direct request:
![image](https://user-images.githubusercontent.com/28047460/108312859-9a808580-71b7-11eb-9ebd-e33f42ef18d7.png)

These are the received response headers:
![image](https://user-images.githubusercontent.com/28047460/108313231-4aee8980-71b8-11eb-9b6d-865623f56695.png)
The `X-DNS-Prefetch-Control` header is only added for direct requests.

One thing I noticed is that the direct request includes a lot of headers but the SystemJS request includes hardly any header. I think these are the headers that make the difference:
![image](https://user-images.githubusercontent.com/28047460/108318177-ac662680-71bf-11eb-8a87-90d435a05276.png)

I'm still wondering why this works for direct requests but not for SystemJS imports.

**Comment by gjhommersom** [comment] 2021-02-18 10:17
After doing some more digging around I discovered that one of the imports does work as expected. 

The difference is that it includes `Cache-Control: public, max-age=0` in the headers. Most likely because it is served by a different server. Most of our files are served by an AspNetCore service but that one isn't.

Modifying the AspNetCore service to also include the header fixes it. Good news. 

But this made me wonder if it works in Edge out of the box. Just because I'm sure Microsoft would make an AspNetCore hosting service and Edge work fine together. And of course it does work without the extra header.

**Comment by joeldenning** [comment] 2021-02-18 23:09
SystemJS simply appends a `<script>` to the page to load resources - it does not control which headers the browser chooses to send in the request, or any caching behavior. The [crossorigin](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) attribute on scripts is a way of controlling authentication headers for scripts, but direct control over the other headers for scripts is not possible in browsers afaik. 

SystemJS exposes the [`createScript` hook](https://github.com/systemjs/systemjs/blob/master/docs/hooks.md#createscripturl---htmlscriptelement), which allows users to customize how the script tag is created, what attributes it has, etc. If you suspect that the problem is in how the script is created, you can customize it via `createScript`.

My understanding is that Chrome intentionally treats going directly to a URL in a browser tab differently than requesting that same URL as part of a web page. My understanding of the difference (which might be wrong or incomplete) is that Chrome is more likely to refetch the resource from server instead of disk cache when you press the refresh button or go directly to a URL, rather than preferring disk cache in that case. Additionally, going directly to a URL in a browser tab often has different request headers sent by the browser than if it's loaded via `<script>`.

As you pointed out, Etag's can help with controlling versioning of resources. The Last-Modified header is another way of controlling it. Generally in production environments, I put the version in the URL itself by updating the import map during deployments, since that ensures the browser will not use a stale version of a file. For example, see https://react.microfrontends.app/importmap.json which versions the modules in the import map.
