### ISSUE TITLE
[webpack interop] Should copy “__esModule” into "ns"

### ISSUE THREAD

**Issue by csr632** [systemjs/systemjs#2090] opened 2020-01-06 12:53 UTC
# description

[minimal reproduce demo](https://github.com/csr632/systemjs-issue-2090)

![image](https://user-images.githubusercontent.com/18747423/71822359-a2728880-30cf-11ea-8210-130af90e0a18.png)
`add` is: 
![image](https://user-images.githubusercontent.com/18747423/71822450-d483ea80-30cf-11ea-9001-0a49bac2764d.png)

# Analysis

https://github.com/systemjs/systemjs/blob/85eb636f46dc4b4a37ffe65affa9e87cfb54d654/src/system-core.js#L105

This line won't iterate and copy `__esModule: true` into `ns` defined by webpack(because `for...in` don't iterate un-enumable property). See this image (debug into systemjs): 
![image](https://user-images.githubusercontent.com/18747423/71818538-45250a00-30c4-11ea-854d-8242058d80a9.png)

The expored object has an un-enumerable `__esModule: true` defined by webpack. webpack will use this to decide how to import "default".
![image](https://user-images.githubusercontent.com/18747423/71819030-a8636c00-30c5-11ea-86da-925ec984cd6a.png)

 But systemjs ignore `__esModule` so I get 
![image](https://user-images.githubusercontent.com/18747423/71819232-42c3af80-30c6-11ea-86f1-3450141f8bfa.png)

**Comment by csr632** [comment] 2020-01-06 12:57
https://github.com/systemjs/systemjs/issues/1967 disscussed about `__esModule`, but I think it is easy for systemjs to keep interop with webpack (copy __esModule into ns object).

**Comment by csr632** [comment] 2020-01-06 14:02
I've create a pr for this.

**Comment by joeldenning** [comment] 2020-01-06 17:23
See related https://github.com/systemjs/systemjs/issues/1933 where this was discussed. Guy Bedford was the original proposer of __esModule but it is now no longer on standards track and he doesn't want SystemJS to depend on it anymore.

Closing this issue since it's something that has already been discussed and decided on in the issue I linked to above. But feel free to comment further on this.

**Comment by csr632** [comment] 2020-01-07 03:12
But is there any other way to support [this simple usecase with webpack](https://github.com/csr632/systemjs-issue-2090)?  I think this is a very basic usecase!

And this usecase is not related to AMD! It is only about "**webpack** bundle **esModule source file** into **systemjs** format, and that **systemjs bundle** can't be consumed by **another systemjs bundle**".

@joeldenning @guybedford

**Comment by csr632** [comment] 2020-01-07 03:21
All webpack need from systemjs is, just "**copy** __esModule flag into ns object if it exists". 

Systemjs don't have to treat `__esModule` specially！Because "copy things from export object to ns object" is what [systemjs already doing](https://github.com/systemjs/systemjs/blob/85eb636f46dc4b4a37ffe65affa9e87cfb54d654/src/system-core.js#L105)!

**Comment by guybedford** [comment] 2020-01-07 03:25
@csr632 it's simple to support in SystemJS yes. The problem is more that it isn't supported in Node.js, and we're trying to make modules work in a way that works universally. Having things work in one environment but not another is not helpful.

**Comment by csr632** [comment] 2020-01-07 03:28
But "copy __esModule flag into ns object **if it exists** in export object" won't break anything in nodejs, I think .

**Comment by guybedford** [comment] 2020-01-07 03:30
@csr632 the problem is that `import { x } from './commonjs.cjs'` in Node.js isn't supported, even with __esModule. This is a big problem. But it is the fact unfortunately.

**Comment by csr632** [comment] 2020-01-07 03:42
"Node.js native loader" don't need  to support `__esModule`. Because `__esModule` is used by **the module loader above node.js native loader**.
For example, in this img,`__webpack_require__.n` is a module loader above systemjs loader:
![image](https://user-images.githubusercontent.com/18747423/71866846-ad1a3580-3142-11ea-9c3f-2d0a69a59b0d.png)

**Comment by guybedford** [comment] 2020-01-07 03:50
Are you outputting the `system` module format from Webpack itself here? Note that a CommonJS module must always be represented by `{ default: module }` no matter if it's bundled in Webpack or otherwise. Because that is the semantic of loading a CommonJS module. The lack of other projects taking a hard stance here is exactly why we're about to get a whole lot of issues like this everywhere.

**Comment by guybedford** [comment] 2020-01-07 03:53
@csr632 unless the original module `MyButton` is an ES module that you are putting into Webpack? Then I would consider this a compatibility issue in Webpack system output. But if it is CommonJS then the output is correct.

**Comment by csr632** [comment] 2020-01-07 03:55
@guybedford  Yes, all I use [is esModule](https://github.com/csr632/systemjs-issue-2090/blob/72132d1d04241871de00476a977ba6eacb6b7b87/src/math-add.js#L1). See this [minimal reproduce repo](https://github.com/csr632/systemjs-issue-2090)

**Comment by joeldenning** [comment] 2020-01-07 06:28
@csr632 one workaround I've employed in the past (not elegant, but works):

```js
export const __esModule = true
```

^ Doing this can often help you interop with webpack better. Doesn't solve every edge case, but solves some. I don't have time to look into your repo at this moment, but might tomorrow. I agree that this is inconvenient.

**Comment by csr632** [comment] 2020-01-07 09:12
@joeldenning 
No, it still doesn't work. [See this branch](https://github.com/csr632/systemjs-issue-2090/tree/manually-export-esm-flag).

**Comment by joeldenning** [comment] 2020-01-09 18:56
I'm looking at the repo now -- I have run into this issue myself since I use SystemJS and webpack a lot. Usually I work around it by not relying on default exports. But that's not a great solution. Will report back with what I find or think of that could solve this.

**Comment by joeldenning** [comment] 2020-01-09 19:58
#### Explanation of behavior

Webpack is already setting `__esModule` on the exported module, but the problem is that the `__esModule` property is not enumerable. Since it is not enumerable, this code in systemjs doesn't add `__esModule` to the systemjs module (or `ns`) object: https://github.com/systemjs/systemjs/blob/7c07d91f9b2e6e6b397cce079f6cce7c005ceb79/src/system-core.js#L105-L111

^ This is what you had already been saying the last few days -- sorry for not catching up with you on this and closing the issue without understanding it.

#### Two solutions
1. Make systemjs treat __esModule differently, but without forcibly adding __esModule to everything. I have done this in #2093

2. Add in a custom extra that adds __esModule to the systemjs module regardless of whether it is enumerable. This one can be used in your code immediately and I've created https://github.com/csr632/systemjs-issue-2090/pull/1 to demonstrate that it works.

```html
    <script src="https://unpkg.com/systemjs@6.1.7/dist/system.js"></script>
    <script>
      (function() {
        const originalInstantiate = System.instantiate;
        System.instantiate = function () {
          return originalInstantiate.apply(this, arguments).then(function (register) {
            return [register[0], function (_export, _context) {
              return register[1](exportWithEsModule, _context)

              function exportWithEsModule(arg1) {
                if (typeof arg1 === 'object' && arg1.__esModule) {
                  _export('__esModule', true)
                }

                _export.apply(this, arguments)
              }
            }]
          })
        }
      })()
    </script>
```

**Comment by csr632** [comment] 2020-01-10 02:47
@joeldenning Thanks for the awesome workaround!

Is there any way I can build [math-add.js](https://github.com/csr632/systemjs-issue-2090/blob/consume-amd/src/math-add.js) into UMD bundle and consume it using `amd extra`?

Currently it doesn't work. [See this branch](https://github.com/csr632/systemjs-issue-2090/tree/consume-amd). The source code use esModule format and it is transpiled into UMD, so I expect systemJS to recognize the "esModule export structure" from the UMD bundle. 

![image](https://user-images.githubusercontent.com/18747423/72121225-683a0d00-3395-11ea-8837-b0ae12a661f0.png)

I guess systemjs could fix this by carefully arranging these `__esModule` and `__useDefault` flag? I don't know.

**Closed** 2020-01-10 18:18 UTC

**Comment by joeldenning** [comment] 2020-01-10 18:26
Released this in https://github.com/systemjs/systemjs/releases/tag/6.1.8

Regarding your new question, check out the discussions at https://github.com/systemjs/systemjs/issues/1967 and https://github.com/systemjs/systemjs/issues/2045

**Comment by joeldenning** [comment] 2020-01-10 18:34
> Is there any way I can build math-add.js into UMD bundle and consume it using amd extra? (So we don't need to build all the existing libraries into systemjs format)

Yes, the AMD extra supports this. However, I'd recommend using System.register format for bundles where you can control the output format. System.register supports aspects of ES modules that UMD does not, including [live bindings]() and named exports. The AMD specification does not have the concept of named or default exports, it just has "the module" which can be an object or a function or a number or anything. ES modules are always objects. By using AMD you're entering into territory where you'll have to think about interop a lot -- ESM and AMD do not have a universal way of interop'ing together.

**Comment by csr632** [comment] 2020-01-13 12:25
I end up using a similar extra to [joel's fix](https://github.com/csr632/systemjs-issue-2090/pull/1) to make AMD works with systemjs. [See this branch](https://github.com/csr632/systemjs-issue-2090/tree/consume-amd).

I know it is bad to mix amd and systemjs. But we just can't afford to migrate everything into systemjs right now. I'm sorry I have to do this.

For anyone facing the same situation, here is the extra:
```js
(function() {
  const originalInstantiate = System.instantiate;
  System.instantiate = function() {
    return originalInstantiate
      .apply(this, arguments)
      .then(function(register) {
        return [
          register[0],
          function(_export, _context) {
            return register[1](exportWithEsModule, _context);
            function exportWithEsModule(arg1) {
              if (
                typeof arg1 === "object" &&
                arg1.__useDefault === true &&
                typeof arg1.default === "object" &&
                // ensure that arg1.default is already an esModule object
                // before we unwrap it
                arg1.default.__esModule === true
              ) {
                _export("__esModule", true);
                _export(arg1.default);
              } else {
                _export.apply(this, arguments);
              }
            }
          }
        ];
      });
  };
})();
```

@joeldenning Maybe this extra can be added into official extra list? (Although this encourage a "bad practice")
