### ISSUE TITLE
System.has and System.get fails for named modules

### ISSUE THREAD

**Issue by khangiskhan** [systemjs/systemjs#2030] opened 2019-09-18 17:16 UTC
This problem was discovered in https://github.com/systemjs/systemjs/issues/2026.

The root of the problem is that before a module is imported `System.resolve('named_module')` resolves to a URL, and after it is imported, it resolves to the ID itself.

A named module loaded through import-map will get stored in the module registry (not the registerRegistry) as a URL, so when you do `System.has("named_module")`, it won't work, you need the resolved URL.  

```html
<script type="systemjs-importmap">
{
   imports: {
      "named_module": "/named_module.js"
  }
}
</script>
<script src="https://cdn.jsdelivr.net/npm/systemjs@6.1.1/dist/system.js"></script>
<script src="https://cdn.jsdelivr.net/npm/systemjs@6.1.1/dist/extras/amd.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/systemjs@6.1.1/dist/extras/named-exports.js"></script>
<script src="https://cdn.jsdelivr.net/npm/systemjs@6.1.1/dist/extras/named-register.js"></script>   
```

```javascript
(async function(){
  console.log(System.resolve('named_module')); // http://localhost/named_module.js

  await System.import('named_module');

  // System.resolve now returns the module from the registerRegistry
  const resolved = System.resolve('named_module'); // changed to "named_module"
  console.log(System.has(resolved)); // false
  console.log(System.get(resolved)); // undefined
})();
```

I see 2 potential fixes:

1. Remove this check in System.resolve:
```
    if (id in this.registerRegistry)
      return id;
```

2. Store named modules in the module registry using the name as the key, instead of the resolved URL

**Comment by joeldenning** [comment] 2019-09-22 17:08
Note that this only applies to named modules that are loaded with System.import(). The behavior is caused by two names being provided for the module -- one name in the import map and one name in the module itself. SystemJS has to choose which name to prefer to use for such modules and is currently preferring the name within the module within System.resolve.

Generally speaking, it's easier/better to just not have names for single modules that you load with `System.import()`. In other words, just call `define([], function() {})` instead of `define('name', [], function() {})`. That would solve your problems. Modules do not need to name themselves when they're already given a name in the import map.

Regarding your proposed solutions:

> 1. Remove this check in System.resolve.
```js
    if (id in this.registerRegistry)
      return id;
```

I think this would break things. The point of named modules is that you're forcing the name to be something that is not a URL. @guybedford might be able to shed more light on why that check exists and what would break if it were removed.

> 2. Store named modules in the module registry using the name as the key, instead of the resolved URL

Unless I'm misunderstanding what you're saying, that behavior is already what is happening. In [your codepen example](https://codepen.io/khangiskhan/project/editor/AzNdxp#), `world` is in the module registry as the id. Not a url.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/5524384/65391580-13ac4c80-dd28-11e9-9887-585d837b8a83.png">

I don't know if the current behavior should be called "expected behavior" or not. Browser specifications do not allow for modules to specify a name for themselves, and as such it's not clear how named modules will interact with the browser's native module registry.

One maybe-solution would be to put the module into two separate slots of the SystemJS module registry -- one as the named module and one as the url module. That way the System.has and System.get would both work. However, I'm not sure if that's the right approach. @guybedford can you comment?

**Comment by joeldenning** [comment] 2019-09-22 17:34
Some discussion outside of github about this:

<img width="909" alt="image" src="https://user-images.githubusercontent.com/5524384/65391964-bbc41480-dd2c-11e9-98da-4c11d87448f7.png">

I'm closing this for now. Like Guy said: "I've yet to hear a comprehensive case of (2) that doesn't have a workaround"

**Closed by joeldenning** 2019-09-22 17:34 UTC

**Comment by khangiskhan** [comment] 2019-09-22 18:41
> > 1. Remove this check in System.resolve.
> 
> ```js
>     if (id in this.registerRegistry)
>       return id;
> ```
> 
> I think this would break things. The point of named modules is that you're forcing the name to be something that is not a URL. @guybedford might be able to shed more light on why that check exists and what would break if it were removed.

Yeah, I tried this out and it does indeed break things.

> 
> Unless I'm misunderstanding what you're saying, that behavior is already what is happening. In [your codepen example](https://codepen.io/khangiskhan/project/editor/AzNdxp#), `world` is in the module registry as the id. Not a url.
> 
> <img alt="image" width="649" src="https://user-images.githubusercontent.com/5524384/65391580-13ac4c80-dd28-11e9-9887-585d837b8a83.png">
> 

The `world` module in my codepen example is stored with the ID because it is defined inline and not behind a `System.import`.

If you look at the other named modules which are loaded via `System.import`, you'll notice they are stored with the URL as the ID on the **first** `System.import()`, and only when they are requested again via a second `System.import()`:

![image](https://user-images.githubusercontent.com/9120188/65392817-d30ffb80-dd46-11e9-81a0-60a2215e4371.png)

Perhaps this is the bug.

**Comment by khangiskhan** [comment] 2019-09-22 18:45
> Some discussion outside of github about this:
> 
> <img alt="image" width="909" src="https://user-images.githubusercontent.com/5524384/65391964-bbc41480-dd2c-11e9-98da-4c11d87448f7.png">
> 
> I'm closing this for now. Like Guy said: "I've yet to hear a comprehensive case of (2) that doesn't have a workaround"

Hi Joel, we do have a use-case where we need to support named-modules, so we can't go with 1).  Can you elaborate on 2), what is the workaround?

**Comment by joeldenning** [comment] 2019-09-22 18:47
The workaround is to not `System.import()` a named module. Either script tag the named module, or don't give it a name.

**Comment by guybedford** [comment] 2019-09-24 22:09
@khangiskhan the way to avoid the normalization issues is to ensure the AMD bundles have been loaded before calling System.import. As in the following:

```js
define('name', ...);
System.import('name');
```

**Comment by frehner** [comment] 2019-09-28 02:22
> @khangiskhan the way to avoid the normalization issues is to ensure the AMD bundles have been loaded before calling System.import. As in the following:
> 
> ```js
> define('name', ...);
> System.import('name');
> ```

Ah, I ran into these issues as well and this solved it for me. Thanks.

(I do want to, long term, change the named AMD bundles we're creating to not-named System bundles, but for backwards compatibility with our current infrastructure they'll have to be named until our migration from SystemJS 0.2 -> 6 is complete)
