### ISSUE TITLE
Module not found: Error: Can't resolve '../system-core'

### ISSUE THREAD

**Issue by jlslew** [systemjs/systemjs#2027] opened 2019-09-13 11:42 UTC
I am bundling s.js with webpack but webpack can't find the module 'system-core' when I `require` 'systemjs/dist/extras/module-types.js'.  I can see that the module 'system-core' exists in the src folder but it is not present in the dist folder.  Is it possible to add the 'system-core' module to the dist folder and publish it to npm?

**Comment by joeldenning** [comment] 2019-09-13 17:51
Are you using system.js or s.js? If you're using system.js, you do not need to include the module-types extra separately, since it is already included into system.js. See [docs that explain this](https://github.com/systemjs/systemjs/blob/master/docs/module-types.md)

Additionally, bundling SystemJS into webpack is generally not recommended. Generally speaking, SystemJS should be loaded into your html file first, and then SystemJS should download the webpack bundle with `System.import('/path-to-webpack-bundle.js')`

Small example:
```html
<script type="systemjs-importmap">
  {
    "imports": {
      "my-webpack-bundle": "/dist/bundle.js"
    }
  }
</script>
<script src="https://cdn.jsdelivr.net/npm/systemjs/dist/system.js"></script>
<script type="systemjs-module" src="import:my-webpack-bundle"></script>
```

However, with all of that said, what you have reported is indeed a bug in systemjs. The dist/extras/module-types.js file should not have an `import` in it, but it does. See https://github.com/systemjs/systemjs/blob/c08c92dcdb0850b999b6cf4c180702e01ae8b04d/dist/extras/module-types.js#L5.

The reason it has an import is that the build process for system.js is okay with having imports in it. But when used as an  extra, it should not use imports at all and instead just patch the `System` global variable.

I'll see if I can put together a fix for this.

**Closed** 2019-09-13 21:45 UTC

**Comment by jlslew** [comment] 2019-09-14 17:19
**The why I am bundling SystemJS with Webpack**
I am using SystemJS as a module loader and Webpack as a module bundler but since I need to require SystemJS then do `SystemJS.import`s in another file, I decided to have 2+ Webpack bundles; one with SystemJS + `SystemJS.import`s, and the others are `libraryTarget: system` bundles.

<details>
    <summary>More details</summary>
I started with system.js but then I saw this `import` attribute and decided to use s.js because it didn't include the global extra

![image](https://user-images.githubusercontent.com/1538744/64911023-d2b3a700-d72d-11e9-90f5-fc393981da39.png)
as well as the module-types extra

![image](https://user-images.githubusercontent.com/1538744/64911094-9896d500-d72e-11e9-95f9-a68625819403.png)
so I `require` the extra but webpack couldn't find the module system-core

![image](https://user-images.githubusercontent.com/1538744/64911173-4ace9c80-d72f-11e9-9be9-972e06ff1a76.png)
</details>
It seems that this patch broke the import of css with either system.js or s.js at least for me

![image](https://user-images.githubusercontent.com/1538744/64911334-591db800-d731-11e9-9d7a-de4d42f8d352.png)

**Comment by kouts** [comment] 2019-09-14 17:35
@jlslew take a look at #1926
How I managed to solve this eventually was to create a custom webpack loader
```
'use strict';
const fs = require('fs');
const path = require('path');
const loaderUtils = require('loader-utils');

module.exports = function(source, map) {
	
    let res = '';
	let to_concat = [
        'node_modules/systemjs/dist/system.min.js',
        'node_modules/systemjs/dist/extras/amd.min.js',
        'node_modules/systemjs/dist/extras/named-exports.min.js',
        'node_modules/systemjs/dist/extras/named-register.min.js',
        'node_modules/systemjs/dist/extras/transform.min.js',
        'node_modules/systemjs/dist/extras/use-default.min.js',
        'node_modules/systemjs-css-extra/dist/css.min.js'
    ];
    for (let i = 0; i < to_concat.length; i++) {
        let contents = fs.readFileSync(to_concat[i]);
        res = res + contents;
    }

    let toret = source.replace(/__SYSTEMJS__/gm, res);
	// console.log('systemjs injected');

    return toret;
};
```
Then in your file just put ```__SYSTEMJS__``` where you want SystemJS to be injected

**Comment by jlslew** [comment] 2019-09-16 06:06
Here is a repository with the bare minimum to show that the css is not loaded anymore; https://github.com/jlslew/webpack-systemjs-test
If you change the version of system.js to 6.1.0, and rebuild, the css file will be loaded

**Comment by joeldenning** [comment] 2019-09-17 20:19
@jlslew this is not a bug in systemjs. I created https://github.com/jlslew/webpack-systemjs-test/pull/1 which shows that.

Like I suggested above -- do not bundle systemjs into webpack. It fixes this problem entirely.

**Comment by joeldenning** [comment] 2019-09-17 20:23
> I am using SystemJS as a module loader and Webpack as a module bundler but since I need to require SystemJS then do SystemJS.imports in another file, I decided to have 2+ Webpack bundles; one with SystemJS + SystemJS.imports, and the others are libraryTarget: system bundles.

This doesn't make sense to me as an explanation for putting webpack into SystemJS. If you load systemjs globally, it is available in all files as a global variable.
