### ISSUE TITLE
Strange/buggy behaviour when commenting out require statements

### ISSUE THREAD

**Issue by stefk** [systemjs/systemjs#926] opened 2015-11-23 18:48 UTC
Suppose you have these files:

(app.js)
```js
require('mod1');

console.log('in app');
```

(mod1.js)
```js
require('mod2');

console.log('in mod1');
```

(mod2.js)
```js
console.log('in mod2');
```

If you import the first one in the browser using:

```js
System.import('app');
```

all of them are downloaded and the console output is, as expected:

```
in mod2
in mod1
in app
```

Now if the require statement of *mod1.js* was commented out:

(mod1.js)
```js
//require('mod2');

console.log('in mod1');
```
 
you would expect only the two first files to be downloaded, and no mention of mod2 in the output. But this is not the case: *mod2.js* is still downloaded and the console reports:

```
in mod1
in app
in mod2
```

(note the wrong order)

This bug happens only when the statement being commented:

1. is in a dependency of the entry point module  (i.e. commenting out statements in *app.js* works as expected)
2. is excluded using line comment syntax (i.e. doing `/*require('mod2')*/` works also as expected)

**Comment by guybedford** [comment] 2015-11-24 10:45
Are you definitely using the latest version of SystemJS here? We certainly have tests for these cases (https://github.com/systemjs/systemjs/blob/master/test/tests/commonjs-requires.js), so I'd be surprised if there was an issue here.

**Comment by guybedford** [comment] 2015-11-24 10:47
Are you sure you don't have something else requiring `mod2`? Because it would only be executed to give the `in mod2` message if there was something actually requiring it.

**Comment by stefk** [comment] 2015-11-24 12:42
@guybedford, I use the version fetched by bower (0.19.6). And no, there's nothing else requiring `mod2`.  I've set up a minimal repo reproducing the issue : https://github.com/stefk/systemjs-issue926. For me, cloning that repo, doing a bower install and accessing the index file in the browser is sufficient to get the behaviour described above.

**Comment by guybedford** [comment] 2015-11-24 12:50
Ah right, this is actually a duplicate of https://github.com/systemjs/systemjs/issues/919 which is fixed pending release.

**Closed by guybedford** 2015-11-24 12:50 UTC
Labels: support
