### ISSUE TITLE
Loading SystemJS through SystemJS

### ISSUE THREAD

**Issue by matthewp** [systemjs/systemjs#344] opened 2015-02-07 14:07 UTC
I have a need to do this:

```js
import System from "systemjs"';
```

So SystemJS needs to be installable.  So a couple of questions/comments.

1. In this scenario global.System should not be overwritten. How do we make that work?
2. How do we know if System is being loaded through a script tag (as currently) or loaded from a Loader? If the latter we need to set `System` as the default export. How can we possibly do this given that exports are static?

This is just to start the discussion.

**Comment by matthewp** [comment] 2015-02-07 14:13
Oh, this should actually be super easy:

```js
System.set('systemjs', System.newModule({'default':System, __useDefault: true}));
```

**Comment by matthewp** [comment] 2015-02-07 14:48
Scratch that last idea, I want to be able to load SystemJS from any loader.

**Comment by guybedford** [comment] 2015-02-08 10:21
Duplicate of https://github.com/systemjs/systemjs/issues/276.

**Closed by guybedford** 2015-02-08 10:21 UTC
