### ISSUE TITLE
Hot-reload fails if exception was thrown during linking of dep modules

### ISSUE THREAD

**Issue by shrinktofit** [systemjs/systemjs#2286] opened 2020-12-11 06:06 UTC
### Demonstration

https://codesandbox.io/s/sad-curran-my4dg?file=/index.js

### Expected Behavior

`System.delete()` could delete the parent module.

### Actual Behavior

`System.delete()` could not delete the parent module.

**Comment by joeldenning** [comment] 2020-12-14 18:24
I looked into this today and here is the relevant code in the delete api:

https://github.com/systemjs/systemjs/blob/ffcc28594b80e4735b27b8fbf4b38126160dfafe/src/features/registry.js#L68-L71

In your case, `load.e` is defined as a no-op function `() => {}`.

The reason that `load.e` is defined is that it gets reset to null after successful execution, but the module didn't successfully instantiate due to the linking error earlier that is caused by `not-found.js` not being found.

You can read more about that at the following code:

https://github.com/systemjs/systemjs/blob/ffcc28594b80e4735b27b8fbf4b38126160dfafe/src/system-core.js#L196-L199

The effect of the code is that it's impossible to delete modules that failed to properly instantiate.

@guybedford can you comment here on why `delete()`'s are not implemented for modules that failed to link + instantiate? Here is my fork of the code sandbox that shows the error:

https://codesandbox.io/s/nostalgic-torvalds-09dky?file=/dep.js

**Comment by guybedford** [comment] 2020-12-14 20:54
This sounds like a bug to me - to explain what the logic should be: it should not be possible to delete a module **while it is still loading**, because this can cause non-determinism in the execution logic. So we check that the module is specifically finished executing, but it sounds like we should be checking if the module is specifically finished execution **or errored** to permit deletion properly here. If the instantiation error state is only in the promise, then the fix should be to set instantiation errors on the instance as the `load.e` value, checking that fits the rest of the logic ok.

**Comment by joeldenning** [comment] 2020-12-15 18:46
I've created https://github.com/systemjs/systemjs/pull/2288 with a fix for this.

**Comment by joeldenning** [comment] 2020-12-16 00:16
Fix released in https://discord.com/channels/@me/689620730614251597/788560116143489035

**Comment by shrinktofit** [comment] 2020-12-16 04:58
@joeldenning thx for your fix

**Comment by shrinktofit** [comment] 2020-12-16 12:49
@joeldenning Seems like sibling dependencies also affected by this problem? The module graph:

```
parent.js         // entry point
dep.js
  not-found.js // cause exception
  dep2.js
```

`dep2.js` can not be deleted:
![image](https://user-images.githubusercontent.com/28807867/102350603-1dcb0280-3fe0-11eb-85eb-b8eb5fd83eb7.png)


Sandbox here: https://codesandbox.io/s/hopeful-mestorf-byfu6

**Comment by joeldenning** [comment] 2020-12-18 23:03
I've confirmed that this is the case, and created a pull request with a test that reproduces the issue: https://github.com/systemjs/systemjs/pull/2291. I'll look into fixing the issue in the next little bit, too. @guybedford your insights would help, too.

**Comment by joeldenning** [comment] 2020-12-18 23:17
A bit more investigation - it appears that the sibling dependency is in the registry as an uninstantiated module. `System.has()` returns true for it, but `System.get()` returns undefined

**Comment by joeldenning** [comment] 2020-12-18 23:33
[This code sandbox](https://codesandbox.io/s/divine-grass-r99r3?file=/index.html) uses native modules and indicates that the SystemJS behavior of downloading the module without instantiating it is the proper behavior. Which is what SystemJS is doing, too. In the sandbox, the b.js file is downloaded, but not instantiated, until we use dynamic import() to load it specifically.

I guess the question is what the proper behavior is for a registry api that has downloaded, but not instantiated, modules in it. I think that it would make sense for `System.has()` to return true, and also for `System.delete()` to delete the module and return true

**Comment by joeldenning** [comment] 2020-12-18 23:36
Apologies for the comment spam here, but I've pushed up a potential fix. Am not sure if it will negatively affect other use cases, but all the tests pass now.

**Comment by shrinktofit** [comment] 2020-12-21 15:41
@joeldenning Thx for the fix, I'll try it later

**Closed** 2020-12-31 20:05 UTC

**Comment by joeldenning** [comment] 2020-12-31 20:09
Fix released in https://github.com/systemjs/systemjs/releases/tag/6.8.3
