### ISSUE TITLE
Package order incorrect when using depcache, possible overrides issue?

### ISSUE THREAD

**Issue by lyptt** [systemjs/systemjs#874] opened 2015-10-27 15:23 UTC
In my app I'm using depcache to speed up the load of all my dependencies. I explicitly want jQuery to load before Angular as otherwise it won't pick it up in time.

It seems that no combination of the dependencies and shim overrides seem to convince depcache to properly order my dependencies.

Here's my override for bower-angular:
```
    "overrides": {
      "github:angular/bower-angular@1.2.29": {
        "dependencies": {
          "jquery": "jspm:jquery@1"
        },
        "shim": {
          "angular": {
            "jquery": "1"
          }
        }
      }
```

I'd expect with this configuration for it to load jQuery *before* angular, however the depcache results don't match up to this:

```
       github:angular/bower-angular@1.2.29
       github:angular/bower-angular@1.2.29/angular.min
       github:components/jquery@1.11.3
       github:components/jquery@1.11.3/jquery
```

Is there something I'm misconfiguring here? It seems to work fine when bundling, or when stripping out depcache completely.

**Comment by guybedford** [comment] 2015-10-27 16:44
Thanks, I think this is a duplicate of https://github.com/systemjs/systemjs/issues/848. I'm aiming to add a fix in the coming SystemJS release within the next week.

**Closed by guybedford** 2015-10-27 16:44 UTC
