### ISSUE TITLE
TypeError: Unexpected anonymous AMD define (FF only).

### ISSUE THREAD

**Issue by gig177** [systemjs/systemjs#835] opened 2015-10-08 15:00 UTC
`TypeError: Unexpected anonymous AMD define: system.src.js (line 3704)`
`TypeError: Unexpected anonymous System.register call system.js (line 2669)`

I have no idea why this happen. Can you explain what does it mean?
Firefox: 41.0.1
Systemjs:  0.19.3

**Comment by guybedford** [comment] 2015-10-08 15:04
Is there any way you can share a test case here?

**Comment by gig177** [comment] 2015-10-08 16:43
[systemjs-unexpected-anonymous-amd-define-issue](/gig177/systemjs-unexpected-anonymous-amd-define-issue)

**Comment by guybedford** [comment] 2015-10-08 16:56
I'm unable to replicate this -
![screen shot 2015-10-08 at 18 55 25](https://cloud.githubusercontent.com/assets/598730/10373513/3ffc6962-6dee-11e5-8231-2d3529985b45.png)

If you're using Firebug it may be due to https://github.com/systemjs/systemjs/issues/814.

**Comment by gig177** [comment] 2015-10-08 17:00
No. I use dev tools. Try to refresh page in aggressive manner.

**Comment by guybedford** [comment] 2015-10-08 17:03
Definitely not getting it at all with cache on or off and a dozen refreshes.

Perhaps try jspm 0.16.12?

**Comment by gig177** [comment] 2015-10-08 17:13
No changes with Systemjs v0.19.4

**Comment by guybedford** [comment] 2015-10-08 17:28
Are you sure your replication is working for you? Did you try `jspm cc && jspm dl-loader`?

**Comment by gig177** [comment] 2015-10-12 08:12
Yes, I'm sure. I did it. Error screenshot - ![error](/gig177/systemjs-unexpected-anonymous-amd-define-issue/blob/master/err.png)

**Comment by soncodi** [comment] 2015-10-12 17:55
Was able to replicate this, in my case after adding `jspm i npm:angular-material-calendar -o "{ main: 'dist/angular-material-calendar' }"` - happens in FF/Linux with Firebug open, per #814. Works fine on Chrome/Linux.

**Comment by guybedford** [comment] 2015-10-12 18:37
@soncodi thanks for sharing a replication. I tried this out, but I just get:

```
Uncaught ReferenceError: angular is not defined
```

On line 3 of `angular-material-calendar.js` when I import `angular-material-calendar` in the browser. Is this definitely working for you in Chrome unbundled?

**Comment by soncodi** [comment] 2015-10-12 23:03
@guybedford: Here's a trimmed-down repro that works on Chrome/Linux breaks on FF/Linux:

https://github.com/soncodi/calendar-error

It seemed to break when I added `dep1` angular module along with an additional `import angular from 'angular';` import from within that dep.

**Comment by atsu85** [comment] 2015-10-13 21:16
This bug is really annoying.
Here is one more sample application (official sample application for Aurelia framework) that can be used to reproduce this issue with FireFox and activated Firebug: https://github.com/aurelia/skeleton-navigation

**Comment by t3hmrman** [comment] 2015-10-14 05:41
So I've been running into this issue also, using FF, and working on a newly started ES6 React app. 

I am not having the problem any more, but the only thing I have changed/done is:
- Disabling the React debugger/helper
- Creating a new tab (probably has nothnig to do with it, of course, but figured I'd include for completeness)

If you don't have the React debugger enabled... not sure what to tell you, but if you do, try turning it off

**Comment by guybedford** [comment] 2015-10-17 07:08
I'm pretty sure this is a duplicate of https://github.com/systemjs/systemjs/issues/814.

**Closed by guybedford** 2015-10-17 07:08 UTC

**Comment by Mordred** [comment] 2015-10-28 07:28
I'm also seeing `TypeError: Unexpected anonymous AMD define` when I use builder with this file:
https://github.com/abpetkov/switchery/blob/master/dist/switchery.js

Problematic is this line: https://github.com/abpetkov/switchery/blob/master/dist/switchery.js#L987

Chrome: 46.0.2490.71

**Comment by guybedford** [comment] 2015-10-28 12:36
@Mordred it doesn't give that error for me at all actually, but it still doesn't bundle properly because of the fact that it has two AMD defines in it. It sounds like a sporadic issue in the AMD design of that file though - anonymous defines plus named defines are not generally supported.

**Comment by vsviridov** [comment] 2015-11-14 02:24
Breaks on Firefox Developer Edition 44.0a2

Having multiple "import" statements produces this error randomly.

**Comment by atsu85** [comment] 2015-11-14 10:10
@vsviridov , root cause of this is:
https://github.com/firebug/firebug/issues/7963

this bug also refers to that issue through following comments:
https://github.com/systemjs/systemjs/issues/835#issuecomment-148892321
https://github.com/systemjs/systemjs/issues/814#issuecomment-151823922
https://github.com/systemjs/systemjs/issues/878#issuecomment-151826900

So if You also want to get it fixed, add a comment to firebug issue - maybe the it gets some more attention :)

**Comment by vsviridov** [comment] 2015-11-14 10:12
@atsu85 no firebug on my install though, just the developer console.

**Comment by guybedford** [comment] 2015-11-15 14:49
Note there are many different causes of this error message. If you're getting this error and don't have an anonymous unexpected define, then a case to replicate would help a lot to look into it further.

**Comment by Bodom78** [comment] 2015-11-22 09:44
I'll add that I upgraded my office project to jspm 0.16.15 (SystemJS 0.19.6) and got the same anonymous System.register call errors with Firefox + Firebug.

Firefox + Developer console works fine.

**Comment by atsu85** [comment] 2015-11-22 15:50
@Bodom78 , see https://github.com/systemjs/systemjs/issues/835#issuecomment-156680765 and add Your comment to the issue that is the root cause, maybe it will get some attention.

**Comment by jithin1987** [comment] 2015-12-03 20:50
I am seeing same issue on Firefox. Restarting FF makes it go away for a while.

**Comment by Vaccano** [comment] 2016-01-11 22:03
I am seeing this issue while debugging.  If I restart firefox it goes away for a bit..  

It is not a Firebug issue.  (I installed firebug hoping it would fix it.  But I had it before I had firebug).

**Comment by guybedford** [comment] 2016-01-11 22:04
@Vaccano if you have a test case that breaks in Firefox but not Firebug, that would be great to see.

**Comment by Vaccano** [comment] 2016-01-11 22:10
@guybedford - Unfortunately it is my full app.  It is internal and not small...  I do have a scaled down version of my app for testing.  But it does not happen with that....  Not sure why...

**Comment by guybedford** [comment] 2016-01-12 08:47
These sorts of issues to only show with large numbers of requests. Any form of replication is very useful but I understand it is tricky to share.

**Comment by atsu85** [comment] 2016-01-12 19:40
@guybedford, 
> @Vaccano if you have a test case that breaks in Firefox but not Firebug, that would be great to see.

actually my experience has always been the other way around, [as i mentioned above](https://github.com/systemjs/systemjs/issues/835#issuecomment-147856210):
> Here is one more sample application (official sample application for Aurelia framework) that can be used to reproduce this issue with FireFox and activated Firebug: https://github.com/aurelia/skeleton-navigation

**Comment by guybedford** [comment] 2016-01-13 11:39
@atsu85 see https://github.com/systemjs/systemjs/issues/878.

**Comment by AckerApple** [comment] 2016-06-07 17:09
I hit a brick wall with this issue but it was because I started using jspm in SFX mode only.

I fixed my issues by going back to basics and was pointed in the direction of this link, which when followed semi-closely, got me out of using SFX mode during development:

http://jspm.io/docs/production-workflows.html

I now only bundle in SFX mode on release to mobile devices

**Comment by emgiezet** [comment] 2016-06-21 12:45
+1

**Comment by guybedford** [comment] 2016-06-21 13:14
@emgiezet as above, replications are welcome.
