### ISSUE TITLE
Support for [].map(System.import)

### ISSUE THREAD

**Issue by krnlde** [systemjs/systemjs#605] opened 2015-07-20 21:40 UTC
Right now the System.import requires a `this` context that is not available in any outer script. Therefore we have to use this wrapper function:

```
// Wanted
[].map(System.import);

// Actually necessary
[].map(function (url) { return System.import(url); });

// Or in ES6
[].map(url => System.import(url));
```
It would be nice if we could remove the `Loader` dependency [here](https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L759) somehow or refactor it that it is not necessary at this step whatsoever.

**Comment by krnlde** [comment] 2015-07-20 21:42
This is also related to #383

**Comment by guybedford** [comment] 2015-07-21 13:47
Have you tried using `[].map(System.import.bind(System))` here?

**Comment by krnlde** [comment] 2015-07-21 16:55
Of course. With no effect.

Please consider this line: https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L759

**Comment by guybedford** [comment] 2015-07-22 12:01
Oh I think I remember this one actually - the binding shouldn't be the problem I don't think. Rather the issue is that `map` provides a second argument with the index as a number, which isn't a valid argument into the System.import statement - `System.import(item, index)`.

**Comment by krnlde** [comment] 2015-07-22 12:04
This isn't the case either since it is the same if I call it 

```
[].map(System.import);

// or

[].map(System.import, undefined);
```

It really is related to the `Loader` context that is required in line 759.

**Comment by guybedford** [comment] 2015-07-22 12:38
Both of those examples would still pass the second argument into the `System.import` function. This is a known issue. Try using -

```javascript
[].map(function(name) {
  return System.import(name);
});
```

Really not too keen on a long debate about bindings, but the way that `this` works is that it references the object the function is a member of.

For example:

```javascript
function logThisName() {
  console.log(this.name);
}
var obj = { name: 'obj' };
obj.log = logThisName;
obj.log(); // logs "obj"
```

That is the `this` binding is fine.

**Comment by krnlde** [comment] 2015-07-22 13:01
Ah the `index` for each element is passed as second argument. Now I see. I thought you meant the `thisArg` from the [map](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/map#Syntax) method itself. Anyway, At least for me the extra callback is no option since it breaks the reading flow because it introduces another (unnessecary) indentation depth - unless there is [another option](383) to pass multiple requirements into System.import.

**Comment by krnlde** [comment] 2015-07-22 13:09
And this is a duplicate of #498

**Comment by guybedford** [comment] 2015-07-24 12:57
Ok, closing for now. This should probably be brought up for the specification, as we aim to support what the specification supports, and not much more.

**Closed by guybedford** 2015-07-24 12:57 UTC

**Comment by krnlde** [comment] 2015-07-24 13:00
I couldn't find a spec. Would you be so kind and paste it here?

**Comment by guybedford** [comment] 2015-07-24 13:25
The loader specification is based on https://github.com/whatwg/loader.
