### ISSUE TITLE
SystemJS Type errors while loading the MFE (6.9.0 breaks named-export behavior)

### ISSUE THREAD

**Issue by saak23** [systemjs/systemjs#2332] opened 2021-05-29 02:21 UTC
@guybedford , @joeldenning ,

Our application is on Angular and we are using Single-spa.
We have recently updated SYSTEM JS version to 6.9.0 from 6.3.3 and deployed to Production. Since then we are seeing below new issue cropped up intermittently and blocking nearly 5% of users loading the application. 
This issue is from https://github.com/systemjs/systemjs/blob/master/src/extras/named-exports.js line number 33-40

TypeError: Cannot read property '__useDefault' of null Stack:TypeError: Cannot read property '__useDefault' of null
TypeError: null is not an object (evaluating 't.__useDefault') Stack:https://creta.state.com/Lib/systemJS.6.9.0.min.js

Can you please suggest me the possible resolution?

**Comment by guybedford** [comment] 2021-05-29 11:58
@saak23 which version did you update from here? It would help to relate the issue to the appropriate change.

**Comment by saak23** [comment] 2021-05-31 05:06
@guybedford : I have updated from 6.3.3 to 6.9.0.
Also, This time I am using Depcache approach for loading JS Assets.
With this I am observing another error which is "Bear Specifier" and  found that Import-map request is not even getting triggered from browser for almost 3% users. 

can you please help is suggesting the resolution? Thanks.

**Comment by saak23** [comment] 2021-06-01 15:43
@guybedford  : Can you please help is suggesting the resolution please? thanks

**Comment by joeldenning** [comment] 2021-06-01 22:37
After some research, it appears the difference is the following line of code, which was introduced in https://github.com/systemjs/systemjs/pull/2245 and released in https://github.com/systemjs/systemjs/releases/tag/6.6.0

https://github.com/systemjs/systemjs/blob/e54d18d95a7e6c9d99190589be2fd2f0d03a5a21/src/extras/amd.js#L59

The problem is that when `module.exports` is `null`, it is still being exported and the named-exports extra can't handle that. I think the best fix would be to only call `_export(module.exports)` if it is not null, as doing so seems disallowed by the System.register [format definition](https://github.com/systemjs/systemjs/blob/master/docs/system-register.md#format-definition).

I'll put together a fix.

**Comment by joeldenning** [comment] 2021-06-01 22:54
Fixed in https://github.com/systemjs/systemjs/pull/2334

**Comment by saak23** [comment] 2021-06-02 05:59
@joeldenning : Thanks a lot for the quick resolution and help.

**Comment by saak23** [comment] 2021-06-02 15:33
@joeldenning  & @guybedford : Can you please merge the code? We are planing to go for production. Thanks

**Comment by saak23** [comment] 2021-06-03 15:31
Hello @joeldenning : Can you please merge the code so that we can proceed further for our deployment? Thanks a lot.

**Comment by joeldenning** [comment] 2021-06-03 22:44
@saak23 repeatedly mentioning us to publish faster is not helpful or necesssary. Your organization can use the modified version of amd.js in #2334 while you wait. You received a fix within a week for your fix, without even providing demonstration of the issue, which is pretty lucky.

**Comment by saak23** [comment] 2021-06-04 17:01
@joeldenning : Completely agree with you. Really thanks a lot.

**Closed** 2021-06-07 18:04 UTC

**Comment by joeldenning** [comment] 2021-06-07 18:12
Fix released in https://github.com/systemjs/systemjs/releases/tag/6.10.0
