### ISSUE TITLE
Problem loading angular2 app written in TS

### ISSUE THREAD

**Issue by KhaosTheory1012** [systemjs/systemjs#434] opened 2015-05-02 17:44 UTC
GET http://localhost:8000/angular2/angular2.js 
es6-module-loader@0.16.5.src.js:2605 GET https://registry.jspm.io/scripts/main.js 404 (Not Found)i @ es6-module-loader@0.16.5.src.js:2605$__Object$defineProperty.value @ es6-module-loader@0.16.5.src.js:2780n @ es6-module-loader@0.16.5.src.js:377t @ es6-module-loader@0.16.5.src.js:365$__Object$defineProperty.value @ es6-module-loader@0.16.5.src.js:2779$__global.upgradeSystemLoader.e.fetch @ system@0.16.7.src.js:731$__global.upgradeSystemLoader.e.fetch @ system@0.16.7.src.js:1754$__global.upgradeSystemLoader.e.fetch @ system@0.16.7.src.js:1851(anonymous function) @ es6-module-loader@0.16.5.src.js:1525D @ es6-module-loader@0.16.5.src.js:1183I @ es6-module-loader@0.16.5.src.js:11427.O.when @ es6-module-loader@0.16.5.src.js:9307.w.run @ es6-module-loader@0.16.5.src.js:8213.e._drain @ es6-module-loader@0.16.5.src.js:973.e.drain @ es6-module-loader@0.16.5.src.js:62t @ es6-module-loader@0.16.5.src.js:268
es6-module-loader@0.16.5.src.js:140 Potentially unhandled rejection [3] Error loading "scripts/main" at https://registry.jspm.io/scripts/main.js
Not Found: https://registry.jspm.io/scripts/main.js (WARNING: non-Error used)

Why is the uri for my main.js set to "https://registry.jspm.io/scripts/main.js"?
Where does this error come from and how to resovle it?

I am using the newest angular2 release and typescript 1.5beta.

**Comment by MajorBreakfast** [comment] 2015-05-02 17:54
Did you include your `config.js`? Likely your paths aren't set.

**Comment by KhaosTheory1012** [comment] 2015-05-02 18:07
How would I write that? Sry I am just starting out with this stuff.
My pathstructure atm is: //build/scripts for all compiled .js files from .ts files and all htmls are in //build

**Comment by MajorBreakfast** [comment] 2015-05-02 18:14
GitHub Wiki, YouTube, tests - all should help. What's happening is that systemjs doesn't know where your modules are. BTW take a look at jspm which can generate and update the config for.

**Comment by KhaosTheory1012** [comment] 2015-05-02 22:44
Uncaught ReferenceError: require is not defined(anonymous function) @ angular2.js:1
(index):21 Uncaught TypeError: System.import is not a function

I installed jspm and changed the script tags in the header:
<script src="../jspm_packages/system.js"></script>
<script src="../config.js"></script>
...
<script src="angular2/angular2.js"></script>

<script>
    System.import('../scripts/main.js');
</script>

System.config({
  "baseURL": "/Warenkorb.html",
  "transpiler": "traceur",
  "paths": {
    "*": "./build/scripts/*.js",
    "github:*": "jspm_packages/github/*.js"
  }
});

config.js:

System.config({
  "map": {
    "traceur": "github:jmcriffey/bower-traceur@0.0.88",
    "traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.88"
  }
});


I don't get this whole system thing. Since I am using typescript nothing works but the angular2-bundle.js from ngconf2015demo and System.import without any systemconfig or jspm stuff.

**Comment by vladima** [comment] 2015-05-03 05:03
Can you provide more context on what are you trying to do and maybe share the code that shows the problem?

**Comment by MajorBreakfast** [comment] 2015-05-03 05:12
Paths should be wildcards
baseURL must be folder, you most likely don't want one anyway

**Comment by KhaosTheory1012** [comment] 2015-05-03 09:13
So I use angular2 (npm install angular2), I used angular2-bundle.js from ngconf2015demo before and it worked. With the "normal" angular2 repo I get the errors I posted before on code like this:

todo.ts:

import {Component, View, bootstrap, For, If} from 'angular2/angular2';

@Component({
    selector: 'todo'
})

@View({
    template: `
        <ul>
            <li *for="#todo of todos">
                {{ todo }}
            </li>
        </ul>
        <p>
        <input #todotext>
        <button (click)="addTodo(todotext.value)">Add ToDo</button>
    `,
    directives: [For]
})

class TodoList{

    todos: Array<string>;

    constructor(){
        this.todos = ["Eat Breakfast", "Walk Dog", "Breathe"];
    }

    addTodo(todo: string){
        this.todos.push(todo);
    }

    doneTyping($event){
        if($event.which === 13){
            this.addTodo($event.target.value);
            $event.target.value = null;
        }
    }
}

bootstrap(TodoList);

index.html:

<!doctype html>
<html>
<head>
    

    <script src="../jspm_packages/system.js"></script>
    <script src="../config.js"></script>

    <script src="ext_scripts/traceur-runtime.js"></script>
    <script src="angular2/angular2.js"></script>
</head>
<body>

<script>
    System.import('../scripts/main.js');
</script>

<cmp></cmp>

</body>
</html>


Errors loading this in chrome devtool:

T http://localhost:8080/angular2/angular2-bundle.js 
es6-module-loader@0.16.5.src.js:2605 GET https://registry.jspm.io/scripts/todo.js 404 (Not Found)i @ es6-module-loader@0.16.5.src.js:2605$__Object$defineProperty.value @ es6-module-loader@0.16.5.src.js:2780n @ es6-module-loader@0.16.5.src.js:377t @ es6-module-loader@0.16.5.src.js:365$__Object$defineProperty.value @ es6-module-loader@0.16.5.src.js:2779$__global.upgradeSystemLoader.e.fetch @ system@0.16.7.src.js:731$__global.upgradeSystemLoader.e.fetch @ system@0.16.7.src.js:1754$__global.upgradeSystemLoader.e.fetch @ system@0.16.7.src.js:1851(anonymous function) @ es6-module-loader@0.16.5.src.js:1525D @ es6-module-loader@0.16.5.src.js:1183I @ es6-module-loader@0.16.5.src.js:11427.O.when @ es6-module-loader@0.16.5.src.js:9307.w.run @ es6-module-loader@0.16.5.src.js:8213.e._drain @ es6-module-loader@0.16.5.src.js:973.e.drain @ es6-module-loader@0.16.5.src.js:62t @ es6-module-loader@0.16.5.src.js:268
es6-module-loader@0.16.5.src.js:140 Potentially unhandled rejection [3] Error loading "scripts/todo" at https://registry.jspm.io/scripts/todo.js
Not Found: https://registry.jspm.io/scripts/todo.js (WARNING: non-Error used)(anonymous function) @ es6-module-loader@0.16.5.src.js:140i @ es6-module-loader@0.16.5.src.js:167u @ es6-module-loader@0.16.5.src.js:189

**Comment by MajorBreakfast** [comment] 2015-05-03 09:40
My advice is to start with something small. Create some files and get them to load. Using systemjs isn't difficult, but you need to roughly understand how evrrything fits together first. Once you're ready bring angular into the mix.

**Comment by KhaosTheory1012** [comment] 2015-05-03 13:39
Uncaught TypeError: Cannot read property 'exports' of undefined
...
Potentially unhandled rejection [2] Error loading "min" at http://localhost:8080/build/scripts/min.js

So atm systemjs loads everything just fine until I start using angular2 and typescript together then I run into these problems with traceur. Everythings loads up just fine but then...

**Comment by vladima** [comment] 2015-05-03 20:05
Ok, I think I know what what is going on.

1. it is possible to make ngconf demo work with current version of Angular2 that is currently available on npm (2.0.0-alpha.21) however beware that 2.0.0-alpha.21 still uses classes as annotations and this will be changed in the future (in fact it is already changed since angular2-bundle.js uses decorator functions to attach metadata). This means that code in ngconfdemo is now more future proof that it will be if we modify it to use Angular2 2.0.0-alpha.21.
2. there is one issue in module format detection in SystemJS, I'll get back to it shortly.

**DISCLAIMER: At this point you should be aware that any changes in the demo code will most likely make it non-compatible with future version of Angular2. If you are willing to keep the modified code - be ready to fix it when new version of Angular2 will be avaiable since the code will most likely be broken**
 
First, get a clean copy of ngconf2015demo: 
```
git clone https://github.com/Microsoft/ngconf2015demo.git
```
Second, install angular2 and its dependencies (rx, zone.js, reflect-metadata). For convinience you can create 'package.json' with the following content 
```json
{
    "name": "ngconf2015demo",
    "version": "1.0.0",
    "dependencies": {
        "angular2": "2.0.0-alpha.21",
        "rx": "2.5.2",
        "zonejs": "angular/zone.js",
        "reflect-metadata": "rbuckton/ReflectDecorators"
    }
}
```
in the root of ngconf2015demo repo and then run:

```
npm install
```
NOTE: Currently this code in bundled in 'angular2-bundle.js'.

Version of angular2 from npm uses commonjs however for some modules SystemJS fails to detect the format correctly and loads them as globals. This happens because Traceur converts 
```javascript
export class OpaqueToken {
/// more code here
}
```

into
```javascript
Object.defineProperties(module.exports, {
  OpaqueToken: {get: function() {
      return OpaqueToken;
    }},
  __esModule: {value: true}
});
// more code here
```

and this usage of `module.exports` is missed by [`cjsExportsRegex`](https://github.com/systemjs/systemjs/blob/master/lib/extension-cjs.js#L8) that expects `module.exports` to be used only in explicit assignments
```javascript
  // require('...') || exports[''] = ... || exports.asd = ... || module.exports = ...
```
As a workaround we'll rebuild angular2 to use `System.register` modules.

Go to 'node_modules/angular2'. First run
```
npm install
```
to install dev dependencies for angular2

then
```
node es6/prod/es5build.js  -s es6/prod/ -d system
```
this command will run pre-packages script 'es5build.js' that will convert 'angular2' code to 'system' modules and drop results in 'system' folder.

'angular2-bundle.js' already includes both classes for annotations and decorator functions that will attach these annotation to targets. Angular2 2.0.0-alpha.21. has only annotation classes but no decorators meaning that we have to add them. Create a file named 'annotations.ts' in the root of the repo  
```typescript
/// annotations.ts
import {Component as ComponentAnnotation, View as ViewAnnotation} from 'angular2/angular2';

declare module Reflect {
    function getMetadata(metadataKey: string, target: Object): any;
}

function addAnnotation(c: any, annotation: any): any {
    (c.annotations || (c.annotations = [])).push(annotation);
    return c;
}

export function Component(arg?: { selector: string, injectables: any[] }) {
    return (c) => {
        let paramTypes = Reflect.getMetadata("design:paramtypes", c);
        if (paramTypes) {
            c.parameters = paramTypes.map(p => [p]);
        }
        else {
            c.parameters = [];
        }
        addAnnotation(c, new ComponentAnnotation(arg))
        return
    }
}

export function View(arg: { templateUrl: string, directives: any[] }) {
    return c => addAnnotation(c, new ViewAnnotation(arg));
}
```

Fix 'todo.ts' to use our custom annotations
```typescript
// replace this line in todo.ts
import {Component, View, bootstrap, For} from 'angular2/angular2';
// with these two lines
import {Component,View} from 'annotations'
import {bootstrap, For} from 'angular2/angular2';
```

Fix 'firebase/angularfire.js': currently this code in this file correctly picks `Component` annotation from the "angular2" module and we need to retarget it to the one from "annotations"

```javascript
// Replace this line
define(["require", "exports", 'angular2/angular2'], function (require, exports, angular2_1) {
// with this line
define(["require", "exports", 'annotations'], function (require, exports, annotations_1) {

// also replace this line
            angular2_1.Component(), 
// with this line
            annotations_1.Component(), 
```

Finally make changes in 'index.html'
1. remove script tag for the 'angular2-bundle.js'
2. add script tags for 'reflect.js' and 'zone.js' as last items in the list.
```html
    <script src="node_modules/reflect-metadata/reflect.js"></script>
    <script src="/node_modules/zone.js/zone.js"></script>
```
3. add entries to `System.paths` for correct path resolution:
```javascript
        System.paths = {
            '*': '*.js',
            'angular2/*': 'node_modules/angular2/system/*.js',
            'rx/*': 'node_modules/rx/*.js',
        };

```

Almost done, what is left is adding 'annotations.ts' into 'tsconfig.json' and compiling '.ts' -> '.ts'
```
node tsc/tsc.js
```

Errors from tsc can be ignored since we don't have proper typing for Angular2 2.0.0-alpha.21.

Run 
```
http-server -o
```
everything should work.

**Comment by KhaosTheory1012** [comment] 2015-05-03 20:43
Okay thanks a lot for your time. I'll try this out as soon as I can.
Tomorrow I hope.

Thanks again. I'll let you know if it worked.

**Comment by friktor** [comment] 2015-05-06 13:41
@vladima your idea isnt work. (
```
"Potentially unhandled rejection [2] Component/<@http://0.0.0.0:8080/annotations.js:8:30
__decorate/<@http://0.0.0.0:8080/todo.js:4:77
__decorate@http://0.0.0.0:8080/todo.js:4:1
AngularFire<@http://0.0.0.0:8080/firebase/angularfire.js:20:23
@http://0.0.0.0:8080/firebase/angularfire.js:13:24
a/c.execute@https://jspm.io/system@0.16.js:5:14414
f@https://jspm.io/system@0.16.js:5:5926
f@https://jspm.io/system@0.16.js:5:5898
l@https://jspm.io/system@0.16.js:5:4563
n/e.instantiate/</<.execute@https://jspm.io/system@0.16.js:5:8149
h@https://jspm.io/es6-module-loader@0.16.5.js:1:19109
m@https://jspm.io/es6-module-loader@0.16.5.js:1:19483
l@https://jspm.io/es6-module-loader@0.16.5.js:1:16727
c@https://jspm.io/es6-module-loader@0.16.5.js:1:17186
i/</<@https://jspm.io/es6-module-loader@0.16.5.js:1:15317
run@http://0.0.0.0:8080/node_modules/zone.js/zone.js:93:16
zoneBoundFn@http://0.0.0.0:8080/node_modules/zone.js/zone.js:70:14
D@https://jspm.io/es6-module-loader@0.16.5.js:1:7437
I@https://jspm.io/es6-module-loader@0.16.5.js:1:7071
[7]</</</</O.prototype.when@https://jspm.io/es6-module-loader@0.16.5.js:1:10745
[7]</</</</w.prototype.run@https://jspm.io/es6-module-loader@0.16.5.js:1:9779
[3]</</</e.prototype._drain@https://jspm.io/es6-module-loader@0.16.5.js:1:1725
e/this.drain@https://jspm.io/es6-module-loader@0.16.5.js:1:1392
t@https://jspm.io/es6-module-loader@0.16.5.js:1:3302
"```

**Comment by vladima** [comment] 2015-05-06 15:37
@friktor ok, can you share your code in its current state (when it is not working) so I can take a look?

**Comment by friktor** [comment] 2015-05-06 15:44
@vladima https://github.com/friktor/ngconf2015demo

**Comment by friktor** [comment] 2015-05-06 15:45
@vladima the components of the angular boot normally. And System.js works fine, but on the anotation.ts swears.

**Comment by vladima** [comment] 2015-05-06 17:30
@friktor for some reason in your repo I don't see any .js files including 'tsc/tsc.js', 'firebase/firebase.js' and 'firebase/angularfire.js' and as a consequence nothing will work. If I copy them from the original ngconfdemo repo and make necessary changes in 'angularfire.js' - demo works like charm

**Comment by guybedford** [comment] 2015-05-21 14:04
Closing, but feel free to continue discussion.

**Closed by guybedford** 2015-05-21 14:04 UTC

**Comment by ravin000** [comment] 2015-05-26 23:02
hi, 
just i make step by step from 
https://angular.io/docs/js/latest/quickstart.html
and as i see it similar
Where is problem?

Test also from ngconf...same
Thanks

**Comment by Tooa** [comment] 2015-06-03 19:48
Hi, 
I had similar problems and was finally able to solve it. Take a look at my [angularjs playground](https://github.com/Tooa/angularjs-playground). It's a working version of the quickstart tutorial. Maybe it could help you.

**Comment by Serhioromano** [comment] 2015-06-18 07:46
I have the same problem. Here are the errors I have.

![](http://serhioromano.s3.amazonaws.com/tmp/2015-06-18_13-01-04.png)

And that is strange. I am using JSPM to install angular2. Here is my `index.html`

```html
<html>
  <head>
    <title>Angular 2 Quickstart</title>
    <script src="assets/jspm/github/jmcriffey/bower-traceur-runtime@0.0.88/traceur-runtime.js"></script>
  </head>
  <body>
    
    <my-app></my-app>
    
	<script src="assets/jspm/system.js"></script>
	<script src="config.js"></script>
  <script src="https://code.angularjs.org/2.0.0-alpha.23/angular2.dev.js"></script>
	<script>
  System.import('build/app');
  </script>
  </body>
</html>
```

and here is my `app.ts`

```js
import {Component, View, bootstrap} from 'angular2';

@Component({
  selector: 'my-app'
})
@View({
  template: '<h1>Hello {{ name }}</h1>'
})
// Component controller
class MyAppComponent {
  name: string;
  
  constructor() {
    console.log(123);
    this.name = 'Alice';
  }
}

bootstrap(MyAppComponent);
```

And this works just fine. But as soon as I delete this

```html
<script src="https://code.angularjs.org/2.0.0-alpha.23/angular2.dev.js"></script>
```

I get those errors. Although in the log I can see that all JS files loaded correctly. I suspect that there is something missing that is installed with JSPM and decorators are not supported.

When I use `http-server -o` to run my app I can see in the log loaded files.

If I delete angular from jspm then it also works fine. I think that `https://code.angularjs.org/2.0.0-alpha.23/angular2.dev.js` is a bundle that contains everything but when you install with JSPM something is missing.

**Comment by schippie** [comment] 2015-06-18 09:48
@Serhioromano I would like to chime in that i am experiencing the exact same issue see:  http://stackoverflow.com/questions/30911861/angular2-jspm-io-reflect-metadata-shim-is-required-when-using-class-decorato

And the code: https://bitbucket.org/schippie/angular-2-jspm-hello-world/src/8af83f2066e5?at=master

**Comment by guybedford** [comment] 2015-06-18 12:49
I've posted an issue at https://github.com/jspm/registry/issues/432 for getting Angular2 to work. The instructions I've provided there will work fine for now though too.

**Comment by robwormald** [comment] 2015-06-18 15:37
@schippie and @Serhioromano https://gist.github.com/robwormald/429e01c6d802767441ec

**Comment by schippie** [comment] 2015-06-18 16:31
@robwormald Ah thank you for your detailed explanation / guide

**Comment by jimthedev** [comment] 2015-06-18 22:32
I am following @robwormald's instructions above and it works great for dev mode (no bundling) and for regular bundling (to dist/main.js). The problem is when trying to bundle an sfx. I get the following error: 

```
Uncaught Module zone.js not present.load @ main.sfx.js:321linkDeclarativeModule @ main.sfx.js:174link @ main.sfx.js:111load @ main.sfx.js:325(anonymous function) @ main.sfx.js:358(anonymous function) @ angular2.js:22loader @ main.sfx.js:339(anonymous function) @ angular2.js:22
```

Oddly the sourcemap is generated and it points back correctly to zone.js@0.5.1.js.

I am using Typescript as my transpiler. 

My config.js looks like this: 

```
System.config({
  "baseURL": "/",
  "defaultJSExtensions": true,
  "transpiler": "typescript",
  "typescriptOptions": {
    "module": "commonjs",
    "emitDecoratorMetadata": true
  },
  "paths": {
    "github:*": "lib/github/*",
    "npm:*": "lib/npm/*",
    "app": "src"
  },
  "packages": {
    "app": {
      "main": "main",
      "defaultExtension": "ts"
    }
  }
});

System.config({
  "map": {
    "angular2": "npm:angular2@2.0.0-alpha.27",
    "es6-shim": "github:es-shims/es6-shim@0.32.2",
    "reflect-metadata": "npm:reflect-metadata@0.1.0",
    "typescript": "github:mhegazy/typescript@v1.5-beta2",
    "zone.js": "npm:zone.js@0.5.1",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:angular2@2.0.0-alpha.27": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "reflect-metadata": "npm:reflect-metadata@0.1.0",
      "rx": "npm:rx@2.5.1",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "zone.js": "npm:zone.js@0.5.1"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:reflect-metadata@0.1.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:rx@2.5.1": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:zone.js@0.5.1": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    }
  }
});

```

My package.js looks like this:

```
{
  "jspm": {
    "directories": {
      "baseURL": "www",
      "packages": "www/lib"
    },
    "dependencies": {
      "angular2": "npm:angular2@^2.0.0-alpha.27",
      "es6-shim": "github:es-shims/es6-shim@^0.32.2",
      "reflect-metadata": "npm:reflect-metadata@^0.1.0",
      "zone.js": "npm:zone.js@^0.5.1"
    },
    "devDependencies": {
      "typescript": "github:mhegazy/typescript@v1.5-beta2"
    }
  }
}
```

And main.html looks like this:

```
<html>
<head>
    <title>Demo App</title>
    <script src="dist/main.sfx.js"></script>
</head>
<body>
    <!-- our angular2 component -->
    <test-app>
        Loading...
    </test-app>
</body>
</html>
```

**Comment by jimthedev** [comment] 2015-06-19 14:46
Per @robwormald in https://github.com/jspm/registry/issues/432#issuecomment-113393723 it looks like the bundling issue is being tracked in https://github.com/systemjs/builder/issues/206 and https://github.com/Microsoft/TypeScript/issues/2233#issuecomment-113368137

My impression is that basically SystemJS needs to throw an error since bundling is not currently supported in TypeScript.

**Comment by vance** [comment] 2016-05-20 18:51
The quickstart guide has a **bug** and will not show the `systemjs.config.js` file.

**Comment by zohaibkathwari** [comment] 2017-01-26 14:45
Well in my case the error is coming from systemjs fetch method i guess, its stated at the end of these files:

Customer.ts file: 
import {Address} from './src/Address'
export class Customer {
    public address: Address = new Address();
    private _customerName: string = "";
    public set CustomerName (name: string) {
        if (name.length == 0) {
            throw "Customer name cannot be empty";
        }
        this._customerName = name;
    }

    public get CustomerName(): string {
        return this._customerName;
    }

    Validate (): void {
        alert('validated sire!');
    }
}
_____________________________________________________________________________________
Address.ts file:
export class Address {
    public streetName: string = "olaaaas";
}
______________________________________________________________________________________
<body>
    <script src="node_modules/systemjs/dist/system.js"></script>
    <script>
        System.config({
            "defaultExtension": 'js'
        });

        System.import('./Customer.js').then(function (exports) {
            var cust = new exports.Customer();
            console.log('exports: ', cust);
        }).catch(function(error){
            console.log(error);
        });
    </script>
</body>
_________________________________________________________________________________
Error from System.imports Catch method on google chrome console:

GET http://localhost:8000/src/Address 404 (Not Found) @ fetch.js:32
(anonymous) @ instantiate.js:157
Error: Fetch error: 404 Not Found
 Instantiating http://localhost:8000/src/Address
 Loading http://localhost:8000/Customer.js
  Loading ./Customer.js
    at fetch.js:37
____________________________________________________________
