### ISSUE TITLE
Still having strange issues with bundles AMD

### ISSUE THREAD

**Issue by msmolka** [systemjs/systemjs#2012] opened 2019-08-30 09:37 UTC
I think it is related to #1980 
I've updated systemjs to latest 6.0.0

And have following files

**index.html**
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Home Page</title>
    <base href="/" target="_blank">
</head>
<body>
    <script type="systemjs-importmap">
        {
            "imports": {
                "jquery": "/lib/jquery/jquery.js",
                "kendo.popup.min" : "https://kendo.cdn.telerik.com/2019.2.619/js/kendo.popup.min.js",
                "kendo.core.min" : "https://kendo.cdn.telerik.com/2019.2.619/js/kendo.core.min.js",
                "test": "/js/test.js"
            }
        }
    </script>

    <script src="https://cdn.jsdelivr.net/npm/systemjs@6.0.0/dist/system.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/systemjs@6.0.0/dist/extras/amd.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/systemjs@6.0.0/dist/extras/named-register.js"></script>


    <script type="text/javascript">
        //<![CDATA[

        const systemResolve = System.resolve;
        System.resolve = async function (id, parent) {
            const resolved = await systemResolve.call(this, id, parent);
            console.log("Resolved: ", resolved);
            return `${resolved}?ver=${Date.now()}`;
        };

        System.import("test");

            //]]>
    </script>




</body>
</html>
```

and
**test.js**
```js
System.register(["jquery", "kendo.popup.min"], function (exports_1, context_1) {
    "use strict";
    var test;
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [
            function (_1) {
            },
            function (_2) {
            }
        ],
        execute: function () {
            test = {};
            exports_1("default", test);
        }
    };
});
//# sourceMappingURL=test.js.map
```

In console I can see:
```
11:28:39.968 Resolved:  https://localhost:44371/js/test.js
11:28:39.978 GET https://localhost:44371/js/test.js?ver=1567157319867
11:28:39.986 Resolved:  https://localhost:44371/lib/jquery/jquery.js
11:28:39.986 Resolved:  https://kendo.cdn.telerik.com/2019.2.619/js/kendo.popup.min.js
11:28:39.995 GET https://localhost:44371/lib/jquery/jquery.js?ver=1567157319867
11:28:39.995 GET https://kendo.cdn.telerik.com/2019.2.619/js/kendo.popup.min.js?ver=1567157319867
11:28:40.621 Resolved:  https://kendo.cdn.telerik.com/2019.2.619/js/kendo.core.min.js
11:28:40.628 GET https://kendo.cdn.telerik.com/2019.2.619/js/kendo.core.min.js?ver=1567157319867
11:28:40.753 Resolved:  jquery
11:28:40.764 GET https://localhost:44371/jquery?ver=1567157319867
11:28:40.770 Error: Error loading jquery?ver=1567157319867 from https://kendo.cdn.telerik.com/2019.2.619/js/kendo.core.min.js?ver=1567157319867
```

For some reason `jquery` from  `kendo.core.min` used by `define("kendo.core.min",["jquery"],e)` is not resolved based on import map.

**Comment by guybedford** [comment] 2019-09-02 16:29
I would suggest just removing the named register extension here actually, it's generally just for bundles containing multiple definitions within them.

The issue is that when using the named register extension, it defines the names registered into the registry directly without resolving them - `jquery` and `kendo.ui`.

It then updates the resolver to no longer resolve those names to URLs, which is why you're seeing `jquery` resolved.

We could update the register extension to always normalize the defined names (like RequireJS), by following the import map. But the problem that we have is that if there is no import map, what should the normalized name be? AMD didn't have a registry of URLs it had a registry of names relative to a baseURL. We don't have that model here, so it has to break down somewhere...

**Comment by guybedford** [comment] 2019-09-02 16:30
To be clear - your app should work without the named register extension.

**Comment by msmolka** [comment] 2019-09-02 17:09
The problem is, some of kendo files are bundles. That’s why I had to define bundles in version 0.2. Without named register some of files are no resolved I believe. 

If you look e.g. into [https://kendo.cdn.telerik.com/2019.2.619/js/kendo.grid.min.js](https://kendo.cdn.telerik.com/2019.2.619/js/kendo.grid.min.. You will see bundle definition. I’m trying to migrate my code from version 0.2. But AMD bundles in kendo is struggling me.

**Comment by guybedford** [comment] 2019-09-02 17:23
So the actual error you're hitting here... is it just that `jquery` is being fetched instead of loaded from the registry?

That sounds like a bug to me.... 

Can you tell me if the following works as a replication of your issue:

/js/jquery.js
```js
define('jquery', [], function () {
  return { j: 'query' };
});
```

app.js
```js
define('app', ['jquery'], function () {
  return { app: {} };
});
```

test.html
```html
<script type="systemjs-importmap">
{
  "imports": {
    "jquery": "/js/jquery.js"
  }
}
</script>
<script>
  System.import('jquery')
  .then(() => {
    return System.import('/app.js');
  });
</script>
```

where `jquery` is not being used as a dependency properly?

**Comment by msmolka** [comment] 2019-09-02 17:36
It is not only that jquery, it depends of what I put into my file. 
Above example is working, 

I will try to give other one a bit more complex.

**Comment by guybedford** [comment] 2019-09-02 17:37
@msmolka I'm asking if you can confirm that is the bug... the goal is to find the most simple replication, not a more complex one please.

**Comment by msmolka** [comment] 2019-09-02 17:38
Aha, sorry, above one is working in this example :(

**Comment by guybedford** [comment] 2019-09-02 17:42
Ah ok, then a replication that captures it would be a huge help. I think the problem is that you're seeing a fetch to `/jquery` which shouldn't be happening in any of the expected SystemJS behaviours.

**Comment by msmolka** [comment] 2019-09-02 17:47
Interesting think, just did one more check with cache busting code... and error appear.

```js
const systemResolve = System.resolve;
        System.resolve = async function (id, parent) {
            const resolved = await systemResolve.call(this, id, parent);
            console.log("Resolved: ", resolved);
            return `${resolved}?ver=${Date.now()}`;
        };
System.import('jquery')
  .then(() => {
    return System.import('/app.js');
  });

```

Without cache busting your code is working. I will check my code without cache busting.

**Comment by guybedford** [comment] 2019-09-02 17:50
It seems like your cache busting may be applying to the internal register names.

Perhaps try:

```js
const systemResolve = System.resolve;
        System.resolve = async function (id, parent) {
            const resolved = await systemResolve.call(this, id, parent);
            console.log("Resolved: ", resolved);
            if (isURL(resolved))
              return `${resolved}?ver=${Date.now()}`;
            return resolved;
        };
System.import('jquery')
  .then(() => {
    return System.import('/app.js');
  });

function isURL(url) {
  try {
    new URL(url);
    return true;
  }
  catch(e) { return false; }
}
```

**Comment by msmolka** [comment] 2019-09-02 18:02
Yes, the error was with cache busting, but there is still strange issue with bundles.

```js
<script type="systemjs-importmap">
        {
            "imports": {
                "jquery": "/lib/jquery/jquery.js",
                "kendo.popup.min" : "https://kendo.cdn.telerik.com/2019.2.619/js/kendo.popup.min.js",
                "kendo.core.min" : "https://kendo.cdn.telerik.com/2019.2.619/js/kendo.core.min.js",
                "kendo.grid.min" : "https://kendo.cdn.telerik.com/2019.2.619/js/kendo.grid.min.js",
                "test": "/js/test.js"
            }
        }
```
Even if I do System.import("kendo.grid.min"). It does not try to get all dependecies. Files is get without error but no dependencies are collected. Dependencies for normal files (no bundle ones) are collected)

**Comment by guybedford** [comment] 2019-09-03 19:16
The problem here is that SystemJS simply doesn't provide workflows for comprehensive named AMD compatibility.

To get this, someone needs to work on it. I've created an issue at https://github.com/systemjs/systemjs/issues/2019 to track.

To be perfectly honest, I have no interest in supporting it personally.

**Comment by msmolka** [comment] 2019-09-03 19:19
I understand, the problem is third party framework, I’m not able to change it. So my only option would be stick with system 0.2

**Comment by guybedford** [comment] 2019-09-03 19:23
I don't see anything wrong with sticking with SystemJS 0.20 for that reason.

**Comment by khangiskhan** [comment] 2019-09-06 16:14
> The problem here is that SystemJS simply doesn't provide workflows for comprehensive named AMD compatibility.
> 
> To get this, someone needs to work on it. I've created an issue at #2019 to track.
> 
> To be perfectly honest, I have no interest in supporting it personally.

@guybedford can you elaborate/clarify what the exact issue is here, and what needs to be solved in #2019 ?  

In @msmolka comment above, `System.import("kendo.grid.min")` breaks because the file/bundle contains multiple defines (multiple modules):

```
//https://kendo.cdn.telerik.com/2019.2.619/js/kendo.grid.min.js
define("util/text-metrics.min",["kendo.core.min"], function(){})
define("kendo.grid.min",["kendo.data.min", <...moredeps>"], function(){});
```

This is related to https://github.com/systemjs/systemjs/issues/1980 where only 1 module per file is supported with `System.import`.

Is #2019 intended to add support for this legacy use case?

**Comment by thiscantbeserious** [comment] 2019-09-09 07:09
> Is #2019 intended to add support for this legacy use case?

#2019 is all about legacy use cases as far as I understand, so I'd guess so.

The current AMD-Extra is more or less aimed at providing support for AMD-Modules generated with tools such as Webpack and Rollup.

Correct me when I'm wrong.

**Comment by guybedford** [comment] 2019-10-13 01:36
Closing as this seems to cover a few issues at this point discussed elsewhere.

**Closed by guybedford** 2019-10-13 01:36 UTC
