### ISSUE TITLE
SSR render of SystemJS stop working with React Redux 7.1.1 but works in 5.0.7

### ISSUE THREAD

**Issue by grvpanchal** [systemjs/systemjs#2353] opened 2021-08-04 07:34 UTC
### Demonstration

React: 16.14.0
ReactDOM/React Native: 16.14.0
Redux: 3.7.2
React Redux: 7.1.1
SystemJS: 6.10.2

Code Sandbox: 

I have code in https://github.com/grvpanchal/react-redux-app-ypsn1g/tree/react-redux-711-not-working

just
```sh
npm install
npm run build
npm run start:ssr
```

### Expected Behavior

```js
const outputReactDom = renderToString(ReduxProvider);
```
The above code should output HTML as a string but the app craches. it works fine with 5.0.7

### Actual Behavior

I get the following error for 7.1.1
```sh
SystemJS SSR app listening at http://localhost:3000
(node:8144) UnhandledPromiseRejectionWarning: Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (https://cdn.jsdelivr.net/npm/@esm-bundle/react@16.14.0/system/react.development.js:1659:16)
    at useMemo (https://cdn.jsdelivr.net/npm/@esm-bundle/react@16.14.0/system/react.development.js:1714:23)
    at ConnectFunction (http://localhost:3000/static/js/mfe-app.system.js:1801:56)
    at processChild (C:\Users\HOME\Documents\projects\react-redux-app-ypsn1g\node_modules\react-dom\cjs\react-dom-server.node.development.js:3043:14)        
    at resolve (C:\Users\HOME\Documents\projects\react-redux-app-ypsn1g\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (C:\Users\HOME\Documents\projects\react-redux-app-ypsn1g\node_modules\react-dom\cjs\react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (C:\Users\HOME\Documents\projects\react-redux-app-ypsn1g\node_modules\react-dom\cjs\react-dom-server.node.development.js:3373:29)
    at renderToString (C:\Users\HOME\Documents\projects\react-redux-app-ypsn1g\node_modules\react-dom\cjs\react-dom-server.node.development.js:3988:27)      
    at C:\Users\HOME\Documents\projects\react-redux-app-ypsn1g\server.js:36:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8144) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate 
the Node.js process with a non-zero exit code.
```

**Comment by joeldenning** [comment] 2021-08-10 20:11
I cloned the repository and was unable to reproduce the problem. I added a console.log to server.js that prints the output of `renderToString` and verified that the string is being rendered. I also checked the package.json and see that react-redux@7.1.1 is being used in the package.json.

Did you find a fix for this since you first reported? Or any further instructions for reproducing the problem?

**Comment by grvpanchal** [comment] 2021-08-12 16:05
I pushed the changes. I was able to fix it by sending the provider to the package. When the Provider was created from the server-side, the context of the provider was not passed which caused the issue. Also, the ReactDOM was loaded twice so I did the following
```js
    const AppJs = await global.System.import('@mfe/app');
    const { default: React } = await global.System.import('react');
    const { renderToString } = await global.System.import('react-dom/server');
    const AppElement = React.createElement(AppJs.default, { store });
    const outputReactDom = renderToString(AppElement);
```

**Closed** 2021-08-12 16:05 UTC
