### ISSUE TITLE
PrepareImport only for provided script to load import-map.json independently

### ISSUE THREAD

**Issue by StanislavVoronov** [systemjs/systemjs#2372] opened 2021-11-09 11:35 UTC
### Description of Proposed Feature
My project add dynamically script of import map json to head tag depending of user role.
PrepareImport loads all found scripts in the head tag. If one import map blocks/pending more other won't completed through the requests finish (we can see it in network tab in console)
My suggestion is create other function which will get script parameter and call function (such as processScripts from import-maps.js), which do all stuff of processScript, but with given script.

### In what way would you use it? to load importmap-json independently 

I can make implementation if I have access

**Comment by joeldenning** [comment] 2021-11-09 21:14
> I can make implementation if I have access

You do not need Github access to contribute to public Github repositories - you can just fork the repo, push to your fork, and open a pull request from your fork to the main repo.

> If one import map blocks/pending more other won't completed through the requests finish

This is expected behavior, and changing it would break things.

Each import map can change the resolution of bare specifiers to URLs. Because of this, SystemJS cannot start loading modules until all import maps have been loaded and processed. Doing otherwise would result in SystemJS loading modules from the wrong URLs in some cases.

Let me know if I am misunderstanding what you're saying, but if I understand the issue correctly this is something that we can't change because it would cause bugs. Closing this issue because of that, but feel free to comment further  and/or reopen.

**Closed by joeldenning** 2021-11-09 21:14 UTC
