### ISSUE TITLE
System.clone not working

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#457] opened 2015-05-21 12:02 UTC
````
var x = System.clone();
x.baseURL = 'http://visuals.guim.co.uk/2015/05/results-interactive-test/1432207400012';
x.import('main').then(function(main) { console.log(main); });
```

The `main` module contains a `System.register('main', …)`, but `main` is an empty object.

If we don't clone System, this doesn't happen—`main` is the correct object. Original System has no config applied.

**Comment by guybedford** [comment] 2015-05-21 12:14
@OliverJAsh this is actually a restriction of `System.register` - it is registering against the global loader.

The thing to do is to reassign the global here to the cloned loader before loading the bundle.

I'm wondering if we should have `System` always refer to the current loader? The issue is if this is a good idea from a spec point of view.

**Comment by OliverJAsh** [comment] 2015-05-21 12:18
> I'm wondering if we should have System always refer to the current loader? The issue is if this is a good idea from a spec point of view.

How would you do this? I'm not sure how you would change the `System.register` calls to use your cloned System.

**Comment by guybedford** [comment] 2015-05-21 12:18
`window.System = clonedLoader`.

**Comment by OliverJAsh** [comment] 2015-05-21 12:35
Hmm, that doesn't seem to fix the problem.

**Comment by OliverJAsh** [comment] 2015-05-21 12:35
```` js
var x = System.clone();
x.baseURL = 'http://visuals.guim.co.uk/2015/05/results-interactive-test/1432207400012';
window.System = x;
x.import('main').then(function(main) { console.log(main); });
```

**Comment by guybedford** [comment] 2015-05-21 13:18
Exactly, did that work ok?

**Comment by OliverJAsh** [comment] 2015-05-21 13:24
No, `main` is still an empty object. I have no idea why.

**Comment by guybedford** [comment] 2015-05-21 13:27
Does `System.normalize('main').then(console.log.bind(console))` normalize exactly to `main`?

As mentioned, defining it as an anonymous register, assuming it actually is one and not a bundle, could be advisable here.

**Comment by OliverJAsh** [comment] 2015-05-21 13:32
> Does System.normalize('main').then(console.log.bind(console)) normalize exactly to main?

Yes, it does.

> As mentioned, defining it as an anonymous register, assuming it actually is one and not a bundle, could be advisable here.

We are looking into this but it would be good to get to the bottom of the issue mentioned above.

**Comment by guybedford** [comment] 2015-05-21 13:45
@OliverJAsh are you able to share an isolated test case then?

Here is my test case that works fine:

test.js
```javascript
System.register('test', [], function(_export) {
  return {
    setters: [],
    execute: function() {
      _export('test', 'test');
    }
  };
});
```

```html
<script>System.import('test').then(console.log.bind(console))</script>
```

**Comment by OliverJAsh** [comment] 2015-05-21 13:59
That works when the register call is in the same file, above the import:

``` js
var System = System.clone();
window.System = System;
System.register('test', [], function(_export) {
  return {
    setters: [],
    execute: function() {
      _export('test', 'test');
    }
  };
});

System.import('test').then(console.log.bind(console))
```

But not when `test` is in a separate file, however:

``` js
var System = System.clone();
window.System = System;
System.register('test', [], function(_export) {
  return {
    setters: [],
    execute: function() {
      _export('test', 'test');
    }
  };
});
```

``` js
// test.js
System.import('test').then(console.log.bind(console))
```

**Comment by OliverJAsh** [comment] 2015-05-21 13:59
I have tried adding a breakpoint about the register call in `test.js`. `window.System` is the cloned version, so I can't make any sense of this.

**Comment by OliverJAsh** [comment] 2015-05-21 14:00
It does work when it's an anonymous `System.register` inside of `test.js` :confused:

**Comment by OliverJAsh** [comment] 2015-05-21 14:04
Sorry, corrected my example now.

**Comment by guybedford** [comment] 2015-05-21 14:09
Thanks I've finally managed to replicate this. Will look into it.

**Comment by guybedford** [comment] 2015-05-21 15:26
Fixed in https://github.com/systemjs/systemjs/commit/f2548d0eb5c1e8876ea2e553f728930be7a92ecc.

**Closed** 2015-06-05 12:52 UTC
Labels: fixed pending release
