### ISSUE TITLE
In-browser transpilation sourcemaps do not work outside of Chrome

### ISSUE THREAD

**Issue by OnurGumus** [systemjs/systemjs#450] opened 2015-05-14 12:53 UTC
When we load our scripts from internet explorer (any version including IE 11) source maps are not being loaded. (Where as chrome loads them properly in my case)
The issue is documented here as well: 
http://colinsalmcorner.com/post/aurelia--debugging-from-within-visual-studio
and he suggests using  require.js as a work around. Please fix it.

**Comment by guybedford** [comment] 2015-05-14 17:45
Sure, we'll look into this and see what we can do.

**Comment by Schibum** [comment] 2015-05-29 10:52
I'm not sure if that's related, but I'm source maps don't work for me with Chrome either, if sources are transpiled and dynamically loaded.
es6-module-loader currently appends !eval to sourceURL to make both sources appear in the debugger. 
However systemjs __eval [overrides sourceURL for dynamically loaded scripts](https://github.com/systemjs/systemjs/blob/master/lib/global-eval.js#L52), so the !eval hack does not work.
[sourceMappingURL](https://github.com/systemjs/systemjs/blob/master/lib/global-eval.js#L23) also fails with the !eval hack, as sourceMappingURL is not on the last line anymore.

It works for me after commenting out [line 52](https://github.com/systemjs/systemjs/blob/master/lib/global-eval.js#L52) or supplying the eval! suffix to [traceur directly](https://github.com/ModuleLoader/es6-module-loader/blob/master/src/transpiler.js#L65) fixed it.

**Comment by lstefano71** [comment] 2015-05-29 15:24
@Schibum thank you for this! I thought I was going crazy... Being a complete newbie at this system.js game I thought I was doing something wrong. Maybe trying to transpile dynamically TypeScript as my first experiment was too much for me to handle. But when things started almost working, I noticed that source maps were all wrong (and thankfully Chrome now shades the bit of code covered by the source map). Commeting out [line 52](https://github.com/systemjs/systemjs/blob/master/lib/global-eval.js#L52) does the trick for me (both in Chrome and IE).

**Comment by guybedford** [comment] 2015-06-01 13:30
I've fixed these up on the master branch now. Note that it sounds like you were running against the SystemJS master release which is not a stable production release yet.

**Comment by guybedford** [comment] 2015-06-05 13:05
Source maps are being correctly output in the latest release. Support for eval source maps in browsers is limited though and Chrome is the best option still.

**Comment by ReverseBlade** [comment] 2015-06-05 13:52
So does it work for IE or not ?

**Comment by guybedford** [comment] 2015-06-05 13:56
I don't have a latest IE VM to test, I only test up to IE10 here. But we're doing everything by the book in the latest release.

**Comment by ReverseBlade** [comment] 2015-06-05 14:14
That's strange IE 10 is practically obsolete. All windows 7 computers that have their updates on has IE 11 installed. 
Anyways does it work for IE 10 ?

**Comment by guybedford** [comment] 2015-06-05 14:16
No not at all - eval-based source maps are a fairly recent support in browsers.

**Comment by ReverseBlade** [comment] 2015-06-05 15:09
This is insane! Then why this issue is closed? The title of this issue says this problem is for IE.
You mean there is no fix?

**Comment by guybedford** [comment] 2015-06-05 15:12
There is nothing we can do apart from including the source map correctly. The rest is up to the browsers.

**Comment by thomas-darling** [comment] 2015-06-06 14:48
Well, @guybedford, this effectively makes systemjs completely useless for everyone working in Visual Studio - which is a very large percentage of developers. I haven't looked into the implementation details here, but somehow other module loaders manage to get this working just fine in IE, so I'm a little baffled by the claim that this is impossible. Would you care to elaborate on why that is, exactly? Surely there must be a way to make this work...

Also, I fully agree with @ReverseBlade that closing this is completely wrong. This issue specifically relates to debugging not working in IE, so how can you possibly justify closing such an important issue without even doing proper testing, and by basically just stating that we are screwed and you don't care about it? This really makes me, and I'm guessing a lot of others, think twice about using systemjs...

I'll go ahead and point the guys from Aurelia to this thread, as I'm sure they are interrested to know that apps build on their new and awesome framework cannot be properly debugged in IE...

**Comment by ReverseBlade** [comment] 2015-06-06 15:00
In addition to above, let me specify one case where debugging on IE engine is a must: That is if you develop Windows Store apps with html  then you cannot use any other browsers to debug things.

**Comment by guybedford** [comment] 2015-06-06 15:00
Sure, I'll reopen this issue. Testing can be done. Browser bugs can be chased up. Contributions welcome.

**Comment by EisenbergEffect** [comment] 2015-06-06 17:37
A few recommendations here for those that are frustrated. Remember, this is an open source project. You are invited to participate and the more you do the more the global collection of developers will benefit. Here are a few things you can do to help Guy out:

* To facilitate him investing the issues, preconfigure a VM for him with all necessary software and a sample project so that it's absolutely effortless for him to investigate the problem. Much of the time solving bugs, in my experience, involves having to set up the correct environment and reproduce the problem. If you make that easy for Guy, it's easier for him to track things down and experiement with solutions.
* Investigate the cause of the issue yourself and provide your findings to Guy. You may not be comfortable fixing the issue or know how, but any research you do could help Guy towards a solution faster.
* Consider fixing the issue yourself and submitting a pull request. This is usually the fastest way to get things fixed. I'm sure Guy would be open to that. The Aurelia team has contributed PRs to jspm/system.js and enjoyed a great working relationship with Guy.
* Consider funding Guy to address issues that are critical for you. On any significant open source project, there are many competing interests and motivations. Many open source leaders are open to companies or individuals funding them to address certain issues at a higher priority level or to implement certain features.
* Place a community bounty on this issue. Maybe you don't know how to or want to fix it but there might be someone else in the community who would do it if there was a reward involved.
* Try to reach out to other developers who you think would be interested in system.js/jspm and see if you can get them involved in this project. As the community grows, more people will be able to assist with these types of issues now and in the future.

**Comment by ReverseBlade** [comment] 2015-06-06 18:29
I think not being able to test something on IE 11 is just ridiculous. Actually this severely damaged my trust to system.js. Come to think of it, the developer of a major javascript framework does not have access to IE 11 to test. If this is the case he should quit developing a framework and quit spending other people's time as well for everyone else's sake. Of course I am in no position to tell what he does. 
To be honest I really wish system.js and aurelia to flourish  from bottom my heart since I believe their developer experience is the very best of anything else. And I strongly believe community should support and help him on his journey. However as a leader of this project he has the greatest responsibility and he should personally fulfill some basic requirements stated above. My two cents to the topic...

**Comment by thomas-darling** [comment] 2015-06-06 19:26
Yeah, to be honest, that was my reaction too, when I found this issue. Just to be clear though, I too think system.js is a really great project, and I truely appreciate all the hard work being put into this.
I would love to help out, but right now we're only in the process of researching potential platforms, and I have to say, that the apparent lack of testing in recent browsers does raise some concerns for us - and so did the initial closing of this issue, as it effectively caused us to spend time trying to debug an already known issue. Situations like that raises concerns about the transparency around issues and limitations. That said, I'm happy it was reopened straight away, so I guess that restores some trust in that process :-)

**Comment by guybedford** [comment] 2015-06-08 17:18
Just to clarify here on the testing front - this project is compatible in IE8+. I test it personally in IE8, 9 and 10 on custom VMs I specially have set up for the purpose, leaving 11 testing for saucelabs tests on the module loader. In-browser debugging support for IE11 is a feature, not a bug. Nowhere do we guarantee that in-browser dynamic loading debugging support is provided in IE. It's great to see that you are interested in the project and want to see greater support like this. As Rob has kindly mentioned, it's very much a matter of priorities.

If you want a feature prioritised, asking nicely is completely the way to go about it.

Chrome only very recently gained full source map support for eval + sourceURL + sourceMappingURL as base64 data URIs. As far as I'm aware IE11 doesn't support this at all, although if someone is able to research the issue more deeply that would be a great. It would be interesting to see if Edge does. 

Note that if you bundle your code, you will get full source maps support in IE. That is the recommended debugging workflow in these cases, which is effectively equivalent to the Browserify style usage.

**Comment by MihaMarkic** [comment] 2015-07-21 16:12
The situation with the Edge is the same. No breakpoints can be hit. I just tried a sample, didn't dig into.

**Comment by Ristaaf** [comment] 2015-09-25 12:27
This is actually the same for just normal JavaScript, when JavaScript files are loaded dynamically with systemjs in Internet Explorer 11 (maybee the same for earlier), breakpoints are not reached. So this problem probably has nothing to do with sourcemaps and typescript, the problem is javascript loaded with systemjs and IE (I have no idea where to put the blame)

For an example of this please see my repository here:
https://github.com/Ristaaf/IEDebugProblem

clone this, run npm install, and npm start, open IE11 and try setting a breakpoint in the app.js file using DevTools it will never get reached. It works fine in Chrome though.

Might have something to do with the polyfill used in IE11 (system-polyfill.js), or it might have to do with IE internals.

**Comment by WorldMaker** [comment] 2015-09-25 20:52
Just in case it helps, I filed an "idea" on the User Voice on the F12 Dev Tools for Edge to maybe trick this from the other side: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/9926640-better-support-for-evaluated-code-source-maps-sys

**Comment by dristic** [comment] 2015-10-29 00:05
It seems like the major issue here is that requirejs utilizes adding `<script>` tags to your page instead of XHR and evaluating the resource coming back. I wonder if this also has any effect on how the browser is caching the script resources coming back as well? It also might be an issue with cross origin resource sharing as well. You may not be able to XHR resources that do not expose the `Access-Control-Allow-Origin: *` header, where as script tags would download those scripts with ease.

Has there been any thought to possibly moving SystemJS to using `<script>` tags as well? Or to make it configurable to use script tags in certain cases?

I agree though, there is not much you can do on the framework side. If IE11 or Edge decides not to support source maps in eval statements then that puts a nail in it as far as I can say other than a major refactor. I could possibly look into moving over to script tags though if that is something @guybedford is interested in.

**Comment by guybedford** [comment] 2015-10-29 19:49
@dristic SystemJS does use script tags automatically when it can. If you set the module format of a module in advance as AMD or System.register, or a global module with defined `exports`, it will use script injection. You can also force script injection via the `scriptLoad: true` meta option as well.

**Comment by dristic** [comment] 2015-10-29 22:55
Oh interesting. @ReverseBlade 's issue could probably be fixed by supplying the `scriptLoad: true` meta option then?

**Comment by jmwnoble** [comment] 2015-10-30 06:44
More than interesting - just got this to work - hitting breakpoints in Visual Studio TS files by adding meta: { "path/tosource/files": { scriptLoad: true }} to config.js.  Good work digging @dristic

**Comment by dristic** [comment] 2015-10-30 17:49
Thanks! Glad you got it to work out. It is definitely a pain working in the future :smile:

For those interested, the issue seems to be that IE browsers support source maps on `<script>` but not `eval()`. Chrome browsers support both.

**Comment by Ristaaf** [comment] 2015-11-02 07:47
Still cannot get a breakpoint to hit with this solution, feels like I am doing something wrong (I can also not see that my script is injected via script tag). Can someone please supply a working example? My example repository (linked earlier in this issue) still does not work with adding `System.config({meta: {"*/*": {scriptLoad: true}}});`

Also tried to add an app folder and putting my app.js and index.html there, and changing to `System.config({meta: {"app/*": {scriptLoad: true}}});` but to no avail. As far as I can see even with this option my app.js file is loaded via xhr.

I also can't see any documentation for scriptLoad in the https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#meta

**Comment by Ristaaf** [comment] 2015-11-02 08:07
After a bit more experimentation, it seems like this really is two different issues, one with sourcemaps and one with dynamically (xhr) loaded scripts loosing their breakpoints on reload in IE (which does not happen at all in chrome or with scripts inserted with script tag in IE).

My example works fine if creating a situation where a breakpoint can be set and then hit without a reload (a button executing a function in the js file for instance).

However I am still interested in getting the scriptLoad to work since that will fix the second problem too.

**Comment by jkristia** [comment] 2015-11-26 19:03
I'm not able to get this working bu adding meta {} tag to system.config. I get 
'unhandled exception at line 1, column 1 in http://localhost:53436/build/<filename>.js; in VS when it loads.
What I'm trying to do is to debug a angular 2 sample project in VS2015

**Comment by jdanyow** [comment] 2015-11-28 06:30
## If you want better FireFox support for debugging sources loaded using dynamic script tags,  please vote for [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1224078)!

**Comment by ReverseBlade** [comment] 2015-11-28 12:36
So funny this bug is noticed this much late. I guess this is the price of being too much chrome oriented as a developer.

**Comment by bakape** [comment] 2016-01-07 15:33
I have a bit different problem, but it is likely related. All my modules are precompiled with Babel and external source maps. The CommonJS dependency modules and global scripts display sources correctly in Chrome. Precompiled register modules don't. However, all 3 module source maps work in Firefox.

**Comment by kinsho** [comment] 2016-01-31 21:13
I'm running into this issue as well on Firebug. So disappointed to see that source mapping does not work at all in the major browsers outside Chrome. 

But this is the cost of using (what I consider to be) cutting edge technology.  I know I made a conscientious decision here to write my application using System.js in order to begin leveraging ES6 functionality as quickly as possible.

I'll see what I could do to work around this issue....

**Comment by mbrowne** [comment] 2016-04-22 13:17
I have so far been unsuccessful at getting source maps to work together with Babel and SystemJS in any way on Firefox. This is my latest attempt, which seems to match the recommendation here to use `scriptLoad`:

	SystemJS.config({
	  transpiler: "plugin-babel",
	  baseURL: "/angular/quickstart/",
	  packages: {
		"app": {
		  "main": "main.js"
		}
	  },
	  meta: {
		"src/*.js": {
		  "scriptLoad": true,
		  "format": "register"
		}
	  },
	  paths: {
		"github:*": "jspm_packages/github/*",
		"npm:*": "jspm_packages/npm/*",
		"app/": "src/"
	  }
	});

But in Firefox that results in the error:

> SyntaxError: import declarations may only appear at top level of a module

(And it doesn't work in Chrome either unless I remove the scriptLoad: true.)

I also tried transpiling my sources with babel-cli with sourcemaps and not transpiling with SystemJS at all, but then SystemJS apparently overrides those sourcemaps with its own, and if I click on an error in the console it takes me to the transpiled JS file rather than the original source. @bakape, how did you get that working in Firefox?

**Comment by mbrowne** [comment] 2016-04-29 22:24
Update: I realized that I misread @guybedford's comment above. Since my modules are in ECMAScript format, I changed `format` to "esm" (and if they were actually in "register" format, then `scriptLoad` would default to true). But it still doesn't work. Having looked a bit in the source, this appears to be an underlying issue in es6-module-loader.

**Comment by soapdog** [comment] 2016-12-20 01:29
This is still happening. I can't use the sourcemaps generated on Microsoft Edge or Firefox (tried stable, dev edition and nightly). The code lists fine in the debugger but setting breakpoints or trying to step thru doesn't. Errors on console shows wrong line numbers and we can't use the trace to navigate. This happens in all non-chrome browsers here.

**Comment by mbrowne** [comment] 2016-12-20 04:22
I haven't tried this yet personally, but have you tried the new "devtools.sourcemap.locations.enabled" in Firefox? See https://github.com/webpack/webpack/issues/1194#issuecomment-255505108

**Comment by soapdog** [comment] 2017-01-03 06:00
@mbrowne just tried that now and the problem persists. Thanks for pointing me to that setting though.

**Comment by JosepMaJAZ** [comment] 2018-05-07 16:05
I was looking into a solution for this, since it has been working fine in Chrome and IE11, but I couldn't get Firefox to work.

Reading comments in several places, I've been able to make Firefox work with a very simple solution.

Add this line into the compilerOptions of the tsconfig.ts file
```
        "mapRoot": "/",
```

With this, and verifying that I had the "show original sources" enabled, as well as activate source maps, the .ts sources showed right away in Firefox 53 (I had this portable version, so I didn't download any more recent one)

**Closed** 2018-09-28 13:28 UTC
Labels: contributions welcome

**Comment by mbrowne** [comment] 2018-09-28 17:05
@guybedford Why was this closed? It doesn’t look like it was resolved (aside from a Typescript-specific workaround).

**Comment by guybedford** [comment] 2018-09-28 17:10
The original issue here was one of evaluated source maps compatibility in older browsers and Firefox, which actually didn't provide support for `eval('source; \n//# sourceMappingURL=data:...')` data URI inline source maps generated by the Babel plugin.

The latest comments seem to be about source maps support in general in browsers it is supported in. This is very workflow specific, and more likely related to the build tool in use than a SystemJS-specific bug since it is simply dumping the above `sourceMappingURL` comment in for in-browser transpilation and relying on existing source maps otherwise.

The in-browser transpilation feature has been moved out of SystemJS core in 2.0 released today, so that this is no longer relevant to 2.0 either.
