### ISSUE TITLE
Live bindings break with +=

### ISSUE THREAD

**Issue by rixo** [systemjs/systemjs#2068] opened 2019-11-14 15:58 UTC
The following code:

~~~js
export let foo = 'foo'

setTimeout(() => {
  foo += 'bar'
}, 100)
~~~

...results in the binding `foo` having the value `"bar"` in modules that import it, instead of expected `"foobar"`.

It works with `foo = foo + 'bar'`.

Reproduction in [this repo](https://github.com/rixo/repro-systemjs).

**Comment by joeldenning** [comment] 2019-11-16 04:19
Thank you for the very clear description and simple repo that shows the problem. I have reproduced the bug. It's a wild one!

This bug is actually a rollup problem, though, and not SystemJS problem. See [this rollup repl example](https://rollupjs.org/repl/?version=1.27.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGxldCUyMGZvbyUyMCUzRCUyMDElNUNuJTVDbmZvbyUyMCUyQiUzRCUyMDElMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJzeXN0ZW0lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==) where rollup is improperly compiling some code to System.register format.

With the following source:

```js
export let foo = 1

foo += 1
```

Here is the actual output:

```js
System.register('myBundle', [], function (exports) {
	'use strict';
	return {
		execute: function () {

			let foo = exports('foo', 1);

			foo += exports('foo', 1);

		}
	};
});
```

But here's the expected output:

```js
System.register('myBundle', [], function (exports) {
	'use strict';
	return {
		execute: function () {

			let foo = exports('foo', 1);

			foo = exports('foo', foo + 1);

		}
	};
});
```

I am tagging @Rich-Harris and @guybedford on this since they maintain and work on rollup. I imagine it would be a hard bug to fix 😁.

I am closing this issue since it's not a problem with SystemJS. Please open an issue on rollup itself and tag me on it so I can see progress on this!

**Closed by joeldenning** 2019-11-16 04:19 UTC

**Comment by rixo** [comment] 2019-11-16 09:17
Yes, obviously, that's Rollup that transform the code in my example. I'm going to report it in the right place. Thanks for your patience!

**Comment by joeldenning** [comment] 2020-01-07 03:22
Related: https://github.com/rollup/rollup/issues/3238

**Comment by guybedford** [comment] 2020-01-07 03:25
Ah, great to see that fix, thanks.
