### ISSUE TITLE
Race condition causes System.import to not resolve nor reject.

### ISSUE THREAD

**Issue by joeldenning** [systemjs/systemjs#1465] opened 2016-10-04 23:10 UTC
We can reproduce this problem every time in our production application, but haven't been able to do so in an example repo.

**Here's what we're doing:**
(Using SystemJS 0.19.37)
1) `System.import('A')` (A has a dependency on B, C, D, E ,F, G)
2) Before that import finishes, do another import: `System.import("B")` (B doesn't have any dependencies)
3) `Promise.all([System.import('B'), System.import('C'), System.import('D')]).then(values => console.log('RESOLVED!')).catch(err => {throw err})`. 

**Expected outcome:**
Either `RESOLVED!` is logged to the console, or an error is thrown.

**Actual outcome:**
The Promise.all is never resolved nor is an error thrown. It appears that the `System.import('C')` promise never is resolved which is why the Promise.all is never resolved.

**What we think is going on:**
We've spent probably ~10 hours trying to figure this out and here's our best attempt at explaining what we think might be happening. Also, we found a hack that worked for our particular case but definitely is not useable generally.

Ideas:
- [linkSet.resolve(startingLoad)](https://github.com/systemjs/systemjs/blob/master/lib/loader-wrapper-start.js#L609) is never called for the linkSet created for System.import('C'). This is a huge red flag because that seems to explain why the System.import promise is never resolved. Our hack was to manually call linkSet.resolve(startingLoad) for our particular module, and we verified that doing this worked.
- Inside of proceedToTranslate, [updateLinkSetOnLoad](https://github.com/systemjs/systemjs/blob/master/lib/loader-wrapper-start.js#L418) isn't getting called on the load for C's System.import. This seems to be because proceedToTranslate [short circuits](https://github.com/systemjs/systemjs/blob/master/lib/loader-wrapper-start.js#L372) if it sees a load that is not in a loading status. In our case, step 1) causes the load for C to not be in a `loading` status by the time that the proceedToTranslate for System.import('C') happens.
- When System.import('A') gets to the proceedToTranslate and then the updateLinkSetOnLoad steps, it does **not** do linkSet.resolve() on the linkSet for System.import('C').

Notes:
We are not sure if this is related or not, but we are using the [sofe](https://github.com/CanopyTax/sofe) loader/plugin which dynamically locates urls. It hooks into `locate`, `normalize`, and `fetch` and actually has a blocking/slow `locate` while it is figuring out where the modules are located. Perhaps the slow `locate` exacerbates a race condition that does not normally appear for most people??

Our attempt to reproduce:
We created an [example repo](https://github.com/joeldenning/system-import-doesnt-resolve) that tries but does not succeed to reproduce the problem.

**Comment by guybedford** [comment] 2016-10-10 14:04
The plugin may well be the cause of exposing the race condition.

I've had to manually fix a lot of race conditions in this loader code, because of the fact that the original loader spec did have race conditions!

https://github.com/systemjs/systemjs/issues/1389 may or may not be related here.

Any help with fixes is very welcome. It's currently my top priority to shift SystemJS over to the new loader base at https://github.com/ModuleLoader/es-module-loader, which would also solve this on the upgrade path.

**Comment by guybedford** [comment] 2016-11-15 12:42
Ok, I'd suggest using [0.20.0-alpha.1](https://github.com/systemjs/systemjs/releases/tag/0.20.0-alpha.1) here if you can, as it includes a rewrite of the linking algorithms that shouldn't have this bug.

**Comment by joeldenning** [comment] 2016-11-16 21:10
I'll try it out sometime. This bug is one that manifests itself in our production app, so probably wouldn't fully commit to 0.20.0-alpha.1. I'll give it a shot, though, and let you know how it goes.

**Comment by guybedford** [comment] 2017-01-25 08:11
This should be fixed in SystemJS 0.20.0 now.

**Closed by guybedford** 2017-01-25 08:11 UTC
Labels: bug
