### ISSUE TITLE
v6 loading module in importmap twice

### ISSUE THREAD

**Issue by viT-1** [systemjs/systemjs#2349] opened 2021-07-14 13:28 UTC
### Demonstration
[demo](https://github.com/viT-1/systemjs-v5-to-v6/tree/5c4b67a174ac32f9bfa0dba133fcacee97a89614) with v5, which is ok, have two messages in console:
`SystemJS bundle file loaded!`
`Nice to see you, world`

### Actual Behavior
When I update package to latest version (6.10.2) and run scripts:
`npm run deploy`
`npm run www`

In browser (`http://localhost:3000/`) I have doubled message:
`Nice to see you, world _bundle-system.js 48:21_`
`SystemJS bundle file loaded! _index.js:6:12_`
`Nice to see you, world _bundle-system.js 48:21_`

**Comment by joeldenning** [comment] 2021-07-16 20:47
I cloned the repo and saw the behavior. The problem is that in systemjs@5, loading a bundle with named registers via System.import resulted in the bundle module being an empty no-op, but in systemjs@6 we return the last named register in the file. So in the example code, `System.import('bundle')` is resolving with an empty placeholder module in systemjs 5 but the app module in systemjs 6.

This is a bug in systemjs that we should fix, but as a workaround you can add `"app": "/bundle-system.js"` to your import map and that fixes it. Also, another workaround is to just call `System.import('bundle')` rather than calling both `System.import('bundle')` and `System.import('app')`.

I'll have to think more about what a fix would look like for this - the systemjs registry usually ensures no duplicate instantiation by resolving all specifiers to URLs and then only instantiating the module for each url once. Named modules violate this by inserting modules into the registry that do not have URLs associated with them. Ideally, we'd somehow connect the named register name with the bundle URL, although it's not clear how that would happen. Another approach could be to mark the registration arrays to avoid double instantiation or something along those lines (a bit ugly).

**Closed** 2021-08-17 16:06 UTC

**Comment by joeldenning** [comment] 2021-08-17 16:10
Fix released in https://github.com/systemjs/systemjs/releases/tag/6.10.3
