### ISSUE TITLE
Server side logging - Elmah

### ISSUE THREAD

**Issue by ajcroteau** [systemjs/systemjs#1383] opened 2016-07-28 17:45 UTC
Hi,

I'd like to be able to use server side logging (Elmah) as a repository for client and server side errors as they occur. I'm assuming this line of code is a catch all for exceptions as they occur through the aurelia app as follows:

SystemJS.import('aurelia-bootstrapper').catch(console.error.bind(console));

I'd like to intercept this somehow and be able to log the exception through an Ajax/API call to the back-end to log the error. Can i add some code here to accomplish this?

Also, when I was attempting to manually throw an exception from a module shown below:

export class Home {
    activate() {
        console.log('Home Activated.');
        throw "Test Exception";
    }
}

I get this error message in the console.

ERROR [app-router] Router navigation failed, and no previous location could be restored.

Thoughts?
Thanks
AJ

**Comment by asapach** [comment] 2016-07-28 17:50
Try this:
* http://www.2ality.com/2016/04/unhandled-rejections.html
* https://gist.github.com/benjamingr/0237932cee84712951a2

**Comment by ajcroteau** [comment] 2016-07-29 11:48
Thank you asapach for your response.

I tried using one of the approaches as follows:

<script>
        SystemJS.import('aurelia-bootstrapper');
        window.addEventListener('unhandledrejection', event => {
            // Prevent error output on the console:
            event.preventDefault();
            console.log('Reason: ' + event.reason);
        });
</script>

Then I created a method to force an exception as follows:

btnClick() {
        var obj = undefined;
        obj.runMethod(); <-- This will throw because you can't execute a method off an undefined object.
}

What i'm seeing is "Uncaught TypeError: Cannot read property 'runMethod' of undefined" in the console. But it's not getting caught by the event listener...

One thing I noticed is the <script> is in my _Layout.cshtml because i'm setting up a web application using web api. The exception is being thrown from a sub-module.

Thanks!!!

**Comment by ajcroteau** [comment] 2016-07-29 11:52
Thank you asapach for your response.

I tried using one of the approaches in my _Layout.cshtml file as follows:

SystemJS.import('aurelia-bootstrapper');
window.addEventListener('unhandledrejection', event => {
      console.log('Reason: ' + event.reason);
});

However, i don't think exceptions are getting caught here... I forced an exception as follows:

export class Search {
    btnClick() {
        var obj = undefined;
        obj.runMethod(); <-- should throw from here...
    }
}

and I see this in the console as follows:

Search.js:4 Uncaught TypeError: Cannot read property 'runMethod' of undefined

**Comment by asapach** [comment] 2016-07-29 14:38
OK, that's a different scenario: a rejected promise can be caused by e.g. an exception thrown inside your module body and my approach will catch that. If you want to catch any other exceptions you should use this: https://developer.mozilla.org/en/docs/Web/API/GlobalEventHandlers/onerror
But this is out of scope of this project.

**Closed** 2016-08-01 16:24 UTC
