### ISSUE TITLE
6.9.0 breaks named-register behavior

### ISSUE THREAD

**Issue by restjohn** [systemjs/systemjs#2331] opened 2021-05-25 19:19 UTC
This basically duplicates [my comment]() on the pull request that caused the issue.

#2329 merged for the 6.9.0 release breaks previous name-register behavior.  After updating to 6.9.0, `System.import()` now resolves the last named-register module instead of the actual module fetched from the URL.  For example, at initialization, I do 
```
const lib1Exports = ...
const lib2Exports = ...
System.register('lib1', [],  _export => {
  return {
    execute: () => {
      _export(lib1Exports)
      // deliberate undefined return because returning something here screws up systemjs
      return void(0)
    }
  }
})
System.register('lib2', [], _export => {
  return {
    execute: () => {
      _export(lib2Exports)
      return void(0)
    }
  }
})
```
Then later
```
const lib3 = await System.import('/libs/lib3.umd.js')
!!lib3.lib2Member // true
```
The above worked as expected with version 6.8.x and the named-register/amd extras.

### Demonstration
Code Sandbox: https://codesandbox.io/s/epic-goldstine-r1qio?file=/index.html
You'll need to comment/uncomment the script elements as necessary to switch between SystemJS versions.

### Expected Behavior
`System.import()` returns the expected module for the given URL.

### Actual Behavior
`System.import()` returns the last module registered with the named-register extra.

**Comment by guybedford** [comment] 2021-05-26 09:03
Thanks for posting, if it's as you say then definitely thats a bug.

**Comment by joeldenning** [comment] 2021-05-26 17:34
I looked at the code sandbox demonstration and see the bug. Thanks for providing the demonstration.

The problem is that amd.js doesn't call `System.register()`, but just overrides `System.getRegister()`. In its overridden `getRegister()`, it only will return the AMD module if the original implementation of getRegister() returns an invalid registration array. In systemjs@6.8, all named registers resulted in invalid registration objects, but that was fixed in systemjs@6.9. I do not think that amd.js' behavior is the right one - counting on `lastRegister` being null or invalid in order for AMD registers to work feels wrong to me.

I think the better solution would be to have amd.js call `System.register()` inside of its implementation of `window.define`. That way the lastRegister stored in system-core would be correct and we would be able to remove much of the amd.js' implementation of `getRegister()`. I explored this a bit in the code sandbox, but would like to hear your thoughts first, @guybedford, on what approach you think is best to solve the problem with amd.js

**Comment by joeldenning** [comment] 2021-06-02 00:16
I have created #2335 which fixes this. I also created https://codesandbox.io/s/busy-goldberg-7z5jz?file=/index.html, which is a fork of the one above, to show that the fix solves the problem.

#2335 is a fairly invasive change (big refactor / maybe considered a rewrite) of amd.js, so if it ends up not being a good approach it's possible we'll have to solve this bug a different way.

**Closed** 2021-06-07 16:34 UTC
Labels: bug

**Comment by joeldenning** [comment] 2021-06-07 18:11
Fix released in https://github.com/systemjs/systemjs/releases/tag/6.10.0
