### ISSUE TITLE
registration[1] is not a function with a project containing libraries

### ISSUE THREAD

**Issue by jwsimms** [systemjs/systemjs#2185] opened 2020-05-07 23:22 UTC
I have been working with SystemJS for sometime without any issues. Our project does not make use of a framework such as Vue, React, or Angular. It is strictly typescript. Recently, we are in the process of importing other libraries, and I took the opportunity to update SystemJS to the latest version and adjust our software to reflect current practices.

After downloading 6.3.1 and modifying our project to use importmap, I received two different errors.

- “Unable to resolve bare specifier”
- “registration[1] is not a function”

```
<script type="systemjs-importmap">
       {
           "imports": {
             "uniFormUI": "./uniFormUI.js"                       
           }
        }
        </script>
        
 <script type="systemjs-module" src="import:uniFormUI"></script>   
 <script src="./node_modules/systemjs/dist/system.js"></script>    
 <script src="./node_modules/systemjs/dist/extras/named-register.js"></script>
```

After days of fiddling with it, I was able to get the import map working, but I used version 6.3.1 of System.js and 6.1.2  of named-register.js.  It was a partial success. Weird! It intermittently worked on my home computer upon startup, generating a promise error attempting to instantiate a class that inherited another. However, my work computer is liking it as I write the description. I don’t get a warm fuzzy feeling with my solution.

To resolve that issue at home, I resorted back by importing my library from the <script> tags, and removing the systemjs-importmap settings. I think the library might not have been loaded before accessing the class, but I am guessing. It would definitely fail more often than succeed.

If I do not use systemjs-importmap, and install 6.2.5 of systemJS, it works perfectly. However, things go off the rails starting from 6.2.6.

```
system.js:533 Uncaught (in promise) Error: Unable to resolve specifier 'uniFormUI' from http://localhost:8080/uniWS/
    at throwUnresolved (system.js:533)
    at SystemJS.systemJSPrototype.resolve (system.js:529)
    at system.js:226

system.js:311 Uncaught (in promise) TypeError: registration[1] is not a function
    at system.js:311
```

Any suggestions would be greatly appreciated as I am running out of ideas. I don't want to mix systemJS versions, and don't want to remain at 6.2.5

I will attempt to create a code sandbox with the failed solution. 
But if I have issues, I have also attached the files of the solution to this issue. 

I have created a new solution in VSCode containing similar errors that I have experienced, ranging from working perfectly to run-time errors.
**just modify index.html for different results by remarking/unremarking scripts**

--------------------------

notes.txt:  describes some of the project setup.
results.txt:  shows the results depending how index.html is defined.
SystemTestWorkspace.code-workspace: VSCode workspace file

[.\MyLib]: library project
  MyClass_A
  MyClass_B extends MyClass_A
[.\_OuputLibraries] the compiled "MyLib" project

[.\MyApp]: application project
  MyClass_C extends MyClass_B
  MyApp
  
[.\MyApp\wwwRoot]: web root folder
  Index.html

[_SystemJSTest.zip](https://github.com/systemjs/systemjs/files/4596191/_SystemJSTest.zip)

**Comment by joeldenning** [comment] 2020-05-08 04:47
I started looking at this tonight, but didn't get very far before I had to stop. I plan on looking at it in more detail tomorrow.

Perhaps the easiest way to fix this is to stop using named modules, as they are not on a standards track and have been the cause of many bugs within SystemJS. Anonymous modules + import maps would not have the issues you're seeing.

All of that said, named modules are still part of SystemJS and are supported. The 6.2.6 release fixed some race conditions with named modules, and that is likely related to the differences between 6.2.5 and 6.2.6 for you. 6.3.0 and 6.3.1 should not have intentionally made any changes to named modules as far as I can tell. However, I'll look into that tomorrow when I delve into this in more depth.

**Comment by joeldenning** [comment] 2020-05-11 18:52
I looked at this again. You should not use Typescript's feature that concatenates all files in a project into a single file. Doing that results in a bunch of named modules in a single file, which is 

Here are a few options that would work better:

1. Output multiple files instead of a single file. To change this, you can switch from `outFile` to `outDir` in your tsconfig. Use [this typescript file extension extra](https://github.com/systemjs/systemjs-examples/blob/master/loading-code/typescript-default-extension/dist/systemjs-hooks/resolve.js) to help resolve extensions. Examples: [1](https://github.com/systemjs/systemjs-examples/tree/master/loading-code/typescript) [2](https://github.com/systemjs/systemjs-examples/tree/master/loading-code/typescript-default-extension)
2. Use a bundler, such as rollup/webpack, to concatenate the files into a single file.

I modified your code and verified that doing these things work.

**Comment by guybedford** [comment] 2020-05-11 21:26
Named registrations are still a feature of SystemJS though - and we should not be hitting any case on named bundles where an error like `registration[1]` is not a function is possible.

@joeldenning does the shared replication successfully reproduce the error message?

**Comment by joeldenning** [comment] 2020-05-11 22:10
> does the shared replication successfully reproduce the error message?

Yes, it does. The zip file has three relevant files: (1) index.html, (2) MyLib.js, and (3) MyApp.js. The MyLib and MyApp files are generated via `tsc` and contain multiple named registers inside of them. MyLib is loaded via `<script src="/MyLib.js"></script>`, and MyApp is loaded via `<script>System.import('/MyApp.js')</script>`.

The error occurs because `firstNamedDefine` is reset to null more quickly in systemjs@>=6.2.6 than it was in 6.2.5. "More quickly" refers to the changes in https://github.com/systemjs/systemjs/pull/2144, where it was switched from a `setTimeout` to `Promise.resolve().then()`. The error occurs because SystemJS core stores the first two arguments as the `lastRegister` and uses that when the extras do not provide a different register. Relevant code below:

https://github.com/systemjs/systemjs/blob/827c644e67ba9c80f409bb2cd68837e3650bd028/src/system-core.js#L62-L64

Notice how the above code does not account for the possibility of named registers, as it assumes the named register extra will patch `getRegister`.

I am not certain why `getRegister` is not being called before firstNamedDefine is being reset in the `Promise.resolve().then()`. The provided zip file contained code that took me a while to figure out, with Windows-specific batch files for copying files and no source control. After spending some time sorting through the project and debugging, I decided the best approach would be to encourage using a more supported workflow instead of spending more hours on it.

**Comment by guybedford** [comment] 2020-05-12 04:31
Ok, we should at least leave this issue open then I think.

**Comment by joeldenning** [comment] 2020-05-12 05:44
Reopened - I don't plan on debugging this further, as named modules have been a sinkhole of many dozens of hours for me in the past. Would gladly welcome help on this one. Also note that creating a new example demonstrating the issue would be helpful, perhaps using the [code sandbox template in the issue template](https://codesandbox.io/s/quirky-antonelli-2kusz?file=/index.html) for easiest debugging.

**Comment by guybedford** [comment] 2020-05-28 19:11
If this comes down to it still being a timing issue, one approach would be to use a more comprehensive "setImmediate" implementation that ensures it runs at the top of the task queue.

See for example the `installPostMessageImplementation` in the old polyfill here - https://github.com/YuzuJS/setImmediate/blob/master/setImmediate.js#L99.

If someone wants to look into this, it could be worth replacing the `setTimeout` with a well-defined `setImmediate` to see if that resolves the issue. Either way it would be a big data point moving forward on this.

**Comment by armandn** [comment] 2020-12-13 10:34
Encountered this issue with version 6.8.1.

I am using systemjs and named-register with code generated by Typescript 4 with `--outfile` and `System.register("Name", ["Dependencies"]`

I am modernizing an existing app and I don't really want to completely change the workflow, so I would really like to be able to be able use the code as generated by Typescript.

Any workarounds I could try?

**Comment by joeldenning** [comment] 2020-12-14 18:42
@armandn the first thing to try is using the named-register.js systemjs extra.

**Comment by Carlosamouco** [comment] 2020-12-23 11:36
I was using version 6.8.1 and I am having the same problem has described by @armandn . I tried  using the named-register.js systemjs extra but with no avail. 
The error appears on line 126 in system-core: 
`var declared = registration[1](_export, registration[1].length === 2 ? {`

**Comment by joeldenning** [comment] 2020-12-23 19:33
Please provide a demonstration of the issue, and we can look into it.

**Comment by joeldenning** [comment] 2021-01-29 00:03
Here's a general explanation of this issue. Sharing for any reading who want to know its cause and how to diagnose:

To help you understand the registration[1] is a not a function error, I'll define what registration is. The registration variable is the array of arguments passed to System.register().

Generally, build tools (including webpack) will produce a bundle that looks like this:

System.register(['react', 'react-dom'], function () {}))
In the above bundle, the registration array is the following:

[['react', 'react-dom'], function () {}]
The first item in the registration array is an array of dependencies. The second item is the function containing the code for your module.

So going back to registration[1] is not a function - this means that the second item in the array is not a function like it should be.

A common reason why this can happen is that a lot of build tools, including webpack and typescript, will output the following if configured to do so:

System.register('library-name', ['dep1'], function () {});
In that case, the second item in the registration array is ['dep1'] which is not a function like SystemJS expects. The named-register.js SystemJS extra modifies the registration array by removing the string 'library-name' so that the remaining items correctly match what SystemJS core expects.

Other SystemJS extras can also impact the registration array. For example, the amd.js SystemJS extra converts a call to define() into a registration array.

To diagnose the cause of the problem in your case, I'd set a break point where the error is occuring, and inspect the registration array. If it has three items instead of two, due to a string name, then the named-register extra might help (or, even better, configure your tool not to output a name. In webpack, this is done by deleting output.library from your config). If it only has two items, but they are not an array of deps + function, then I'd figure out which module's registration array you're looking at (the load object in the devtools will help you see that) and then try to figure out why the registration array is wrong. In doing so, you might come across the getRegister() function within SystemJS - that is the function called within SystemJS core which must return the registration array. Generally the script-load.js file is where getRegister() is invoked.

**Comment by lili21** [comment] 2021-04-25 18:50
Run into the same issue. I create a [repo](https://github.com/lili21/systemjs-issue) to reproduce the error

**Comment by joeldenning** [comment] 2021-04-26 18:28
This is because you're loading the UMD version of react with the systemjs `amd.js` extra. When you add the AMD extra, it no longer throws the error. Without the AMD extra, systemjs tries to load react as a global variable which is susceptible to race conditions. I do not recommend using the named-register or global.js extras as they are both susceptible to race conditions.

Here's a PR that fixes your demonstration repo. https://github.com/lili21/systemjs-issue/pull/1

**Comment by guybedford** [comment] 2021-04-28 18:48
@joeldenning can we mark this as a duplicate of https://github.com/systemjs/systemjs/issues/2293 or do you think we should track separately?

**Comment by joeldenning** [comment] 2021-04-29 22:28
Yeah we can close as a duplicate.

**Closed by joeldenning** 2021-04-29 22:28 UTC
