### ISSUE TITLE
SystemJS Load errors while loading the JS Assets

### ISSUE THREAD

**Issue by saak23** [systemjs/systemjs#2304] opened 2021-02-25 22:31 UTC
Question
@guybedford, @joeldenning , @kouts  and all,
I have an angular app which uses systemjs. It has multiple assets - e.g. vendor, main, runtime, polyfills & polyfills-es5.
I wanted to download these assets in parallel for performance reasons so I used Promise.All.  

Promise.all([ System.import('runtime'), System.import('polyfills'), System.import('polyfills-es5'), System.import('vendor'), System.import('main') ]) .then(function(modules) { ... })

With above approach, sometimes (intermittently) seeing load errors like below in production,

Error#1:
Message: Loader error occurred:: TypeError: undefined is not an object (evaluating 'e') Stack:https://my.cosmos.com/L/system.1.1.0.min.js
Error#2
loading https://my.cosmos.com/A/d/vendor.js (SystemJS Error#3 https://git.io/JvFET#3) Stack:https://my.cosmos.com/L/system.1.1.0.min.js
Error#3
Loader error occurred:: Error: Error loading https://my.cosmos.com/A/d/vendor..js (SystemJS Error#3 https://git.io/JvFET#3) Stack:Error: Error loading https://my.cosmos.com/A/d/vendor.js (SystemJS Error#3 https://git.io/JvFET#3)
Error#4
Loader error occurred:: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode Stack:SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

Now we are using "depcache". But still seeing these errors.

Is there an alternative or recommended solution that I can use? I feel like I'm missing something obvious.

**Comment by joeldenning** [comment] 2021-02-26 00:01
### Some background

Webpack has two ways to do code splitting: [dynamic import](https://webpack.js.org/guides/code-splitting/#dynamic-imports) and the [`"optimization"` config](https://webpack.js.org/guides/code-splitting/#splitchunksplugin). Angular CLI uses the optimization config, with dynamic import possible in project code as well. The output chunks produced by the optimization config are not in System.register format and do not register modules to SystemJS (see https://github.com/webpack/webpack/issues/8833#issuecomment-468181544). In webpack, only the entry chunks (not the chunks created by the optimization config) are truly in-browser modules loadable by SystemJS.

With this context in mind, the next thing to discuss is webpack's module registry. Webpack uses the global variable `window.webpackJsonp` to store all of its modules. Those modules are separate from SystemJS modules. Each webpack chunk will either create or update the `webpackJsonp` global variable with its new modules. The order in which the modules are added and executed can matter, as chunks can have interdependencies.

Generally, webpack's `optimization` config is paired with [html-webpack-plugin](https://webpack.js.org/plugins/html-webpack-plugin/#root), which automatically injects a `<script>` for each of the chunks. html-webpack-plugin also guarantees that the `<script>` elements are in the correct order.

In the case of microfrontends, pairing the `optimization` config with html-webpack-plugin is not an option, since the idea is to incorporate separate microfrontends into one html file instead of each having their own.

### Problem

In your code, you're using `Promise.all()` to load each of the chunks, which does not guarantee order. Because of this, the order in which the webpack chunks access `webpackJsonp` will vary depending on network conditions. That race condition is the cause of your problems.

### Solution

*Option 1:*

Disable webpack's `optimization` config for your project. See https://github.com/single-spa/single-spa-angular/blob/e9f14ee1b8e021122cc66e9c4a0b0802e2938548/libs/single-spa-angular/webpack/index.ts#L81-L82

Use dynamic imports as the only method of code splitting.

*Option 2:*

Ensure correct order of execution, instead of using Promise.all. I don't know the correct order of execution for the angular chunks, but here's my guess:

```js
Promise.all([System.import('runtime'), System.import('polyfills'), System.import('polyfills-es5')])
  .then(() => System.import('vendor'))
  .then(() => System.import('main'));
```

To try to improve the waterfall nature of that flow, you can leverage SystemJS depcache, or inject `<link rel="preload" as="script">` elements manually. iirc, the way that depcache works is by inserting`<link rel="preload">` elements.

Closing this issue as I believe to have answered the question. Feel free to respond further or reopen.

**Closed by joeldenning** 2021-02-26 00:01 UTC
