### ISSUE TITLE
Chrome deprecations

### ISSUE THREAD

**Issue by robertbaker** [systemjs/systemjs#657] opened 2015-08-04 19:05 UTC
```'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
system.src.js:3826 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.```

**Comment by guybedford** [comment] 2015-08-05 11:18
Thanks, these warnings should be fixed in SystemJS 0.16. Although I just noticed a typo in https://github.com/systemjs/systemjs/commit/afae50e3422d4df51e0873dc8878a8b7b133ab72 so maybe not for `webkitIndexedDB` just yet.

**Closed by guybedford** 2015-08-05 11:18 UTC

**Comment by lookfirst** [comment] 2015-08-13 22:44
Still seeing this with 8.10

**Comment by lookfirst** [comment] 2015-08-13 22:45
```
system.src.js:3987 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
system.src.js:3987 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
```

**Comment by lookfirst** [comment] 2015-08-13 22:46
@guybedford

**Comment by guybedford** [comment] 2015-08-15 18:36
Line 3987 of SystemJS 0.8.10 is an empty line, are you sure you're running that version?

**Comment by lookfirst** [comment] 2015-08-15 18:48
Weird, now it is reporting line 4033. It is the next to last bootstrap(); line near the bottom of the file.

**Comment by guybedford** [comment] 2015-08-15 19:37
I'm definitely not getting these at all - note the fix is easily visible by `webkitIndexedDB` being included on this line https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L2450. Is that present in your source code?

**Comment by cayuu** [comment] 2015-08-19 13:45
FYI seeing this too, but only on Chrome (Safari is quiet) - the warning is calling out  `bootstrap()` on [line 4050](https://github.com/systemjs/systemjs/blob/0c9bef797f69e975b8596b628a28068f691d120e/dist/system.src.js#L4050) using build 0c9bef797f whatever that's worth. Can confirm the global ignore is present in the system.js loaded.

- Chrome 44.0.2403.155 (64-bit) (OSX)
- System.js v0.18.11 
- (setup through jspm v0.16.0)

**Comment by cayuu** [comment] 2015-08-19 14:20
This may be tied directly to React. A clean System.js install and some generic (DOM + logic) code **doesn't pop the warning**. But drop a `React.render` and hello nurse. Smallest reproducible example:

```bash
mkdir demo; 
cd demo;
npm init; # defaults
npm install jspm; #0.16.0
./node_modules/.bin/jspm init; # defaults
./node_modules/.bin/jspm install react; #0.13.3
```

- index.html

```html
<body>
  <script src="jspm_packages/system.js"></script>
  <script src="config.js"></script>
  <script>
    System.import('index.js')
  </script>
</body>
```

- index.js

```js
import React from 'react'

class Demo extends React.Component {
  render () {
    return <div>Demo</div>
  }
}

React.render(<Demo />, document.querySelector('body'))
```

Gives this on once React.render kicks in:

> 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead. system.src.js:4050 
> 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead. system.src.js:4050 

Not sure this is System.js's problem. Haven't tried with React 0.14-betas.

**Comment by lookfirst** [comment] 2015-08-19 15:57
Right... I still see it all the time. Haven't had a chance to grep a bundle for it yet...

I think the warning propagates up through SystemJS cause that is what loaded it.

I'm angularjs based, so it is probably some third party lib somewhere still using it.

**Comment by sc0ttwad3** [comment] 2015-09-11 05:28
Tried it with the latest react@0.14.0-rc1 and react-dom@0.14.0-rc1 and same:

    system.src.js:4208 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.

    system.src.js:4208 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.

**Comment by guybedford** [comment] 2015-09-11 10:31
@sc0ttwad3 see https://github.com/systemjs/systemjs/issues/714#issuecomment-136980165 for the config you need to add here.

**Comment by sc0ttwad3** [comment] 2015-09-14 00:00
__Still getting the warnings__ even after making the addition to __config.js__  (as indicated in #714 (comment)).  Same problems.  Thanks for spending time looking into this, and I'll continue investigating myself, but so far no luck...  Here's further details...

The 'meta' section addition made to __config.js__ ...

#### config.js ####
    System.config({
      baseURL: "/",
      defaultJSExtensions: true,
      transpiler: "babel",
      babelOptions: {
        "optional": [
          "runtime",
          "optimisation.modules.system"
        ],
        "blacklist": []
      },
      paths: {
        "github:*": "jspm_packages/github/*",
        "npm:*": "jspm_packages/npm/*"
      },
      meta: {
        "core-js/modules/$.global": {
          "esmExports": false
        }
      },
      map: {
        "babel": "npm:babel-core@5.8.23",
        "babel-runtime": "npm:babel-runtime@5.8.20",
        "core-js": "npm:core-js@1.1.4",
        "react": "npm:react@0.14.0-rc1",
        "react-dom": "npm:react-dom@0.14.0-rc1",
        "whatwg-fetch": "npm:whatwg-fetch@0.9.0",
        "github:jspm/nodelibs-buffer@0.1.0": {
          "buffer": "npm:buffer@3.4.3"
        },

        ....  lines omitted ....

        "npm:util@0.10.3": {
          "inherits": "npm:inherits@2.0.1",
          "process": "github:jspm/nodelibs-process@0.1.1"
        }
      }
    });


#### DevTools console

    system.src.js:4208 --- 'window.webkitStorageInfo' is deprecated. Please use 'navigator.    webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
    
    system.src.js:4208 --- 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.



The problems come from inside a call to *bootstrap()* near the end of __system.js__ (line 4208 in system.src.js)...

#### system.src.js ####
    /*
     * SystemJS v0.18.17
     */
    (function() {
    function bootstrap() {(function(__global) {
    
      .... lines omitted ....
    
    
    if (typeof Promise === 'undefined' || !hasURL) {
      // document.write
      if (typeof document !== 'undefined') {
        var scripts = document.getElementsByTagName('script');
        $__curScript = scripts[scripts.length - 1];
        var curPath = $__curScript.src;
        var basePath = curPath.substr(0, curPath.lastIndexOf('/') + 1);
        window.systemJSBootstrap = bootstrap;
        document.write(
          '<' + 'script type="text/javascript" src="' + basePath + 'system-polyfills.js">' + '<' + '    /script>'
        );
      }
      // importScripts
      else if (typeof importScripts !== 'undefined') {
        var basePath = '';
        try {
          throw new Error('_');
        } catch (e) {
          e.stack.replace(/(?:at|@).*(http.+):[\d]+:[\d]+/, function(m, url) {
            basePath = url.replace(/\/[^\/]*$/, '/');
          });
        }
        importScripts(basePath + 'system-polyfills.js');
        bootstrap();
      }
      else {
        bootstrap();  // <=====   This call identified by DevTools as error source
      }
    }
    else {
      bootstrap();
    }
    

    
    })();    

I'll continue investigating...

**Comment by katrotz** [comment] 2015-10-01 08:25
@sc0ttwad3 it looks like you are missing the `library` in the the meta definition:
```
meta: {
    "core-js/library/modules/$.global.js": {
      "esmExports": false
    }
  }
```

**Comment by sc0ttwad3** [comment] 2015-10-04 13:06
@katrotz Good catch. Thanks for spotting that!

**Comment by 5an1ty** [comment] 2015-11-07 16:58
Same issue on the bootstrap method for me... I have the correct meta settings added to config.js.
Using the latest JSPM beta...

**Comment by onlywei** [comment] 2015-12-22 15:24
@guybedford I looked at the line https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L2450 you pointed out in the source code, and there is no reference to webkit-anything there. I'm still getting both deprecation warnings. I also don't use React at all.

**Comment by sc0ttwad3** [comment] 2015-12-24 18:42
​Veaceslav,​

Added the missing meta definition to *config.js* and it took care of the
problem:

*meta: {
    "core-js/library/modules/$.global.js": {
      "esmExports": false
    }
  }
*


I'm curious why even after *jspm init*, and many modules/packages installed
via jspm, that meta definition is never added to the config.js.  Any
pointers to when/how is it supposed to be add as entry -- maybe something
I'm missing that then necessitates me having to manually add it?

**Comment by guybedford** [comment] 2015-12-27 20:50
@sc0ttwad3 arbitrary SystemJS package configuration is not supported in jspm package.json until jspm 0.17.
