### ISSUE TITLE
Chain of Dynamic Imports

### ISSUE THREAD

**Issue by pchainho** [systemjs/systemjs#1954] opened 2019-06-11 21:48 UTC
I'm trying to dynamically import modules one after the other in a chain of promises without success:

```
var load = function (url) {
                return new Promise(function (resolve, reject) {
                    System.import(url).then(function (result) {
                        var instance = new result.default();
                        resolve(instance);
                    }).catch(function (reason) {
                        console.error(reason);
                        reject();
                    });
                });
            }

            load(url1).then(function (module) {
                console.log('import1 result ' + module.name);
                load(url2).then(function (module) {
                    console.log('import2 result ' + module.name);
                }).catch(function(reason) {
                    console.error('import2 error ' + reason);
                })
            })
        };
```

But if I put in sequence it works:

```
            load(url1).then(function (module) {
                console.log('import1 result ' + module.name);
            }).catch(function(reason) {
                    console.error('import1 error ' + reason);
                })

            load(url2).then(function (module) {
                    console.log('import2 result ' + module.name);
                }).catch(function(reason) {
                    console.error('import2 error ' + reason);

                })
```

How can I use SystemJS dynamic imports in a chain of promises like in the first example?

**Comment by joeldenning** [comment] 2019-06-12 17:24
Promises can be chained by returning a new Promise from a `.then`.

```js
System.import(url1).then(mod1 => System.import(url2)).then(mod2 => console.log(mod2))
```

Or if you need them all the values at once at the end:
```js
Promise.all([System.import(url1), System.import(url2)]).then(values => {
  const [mod1, mod2] = values
  console.log(mod1, mod2)
})
```

However, usually instead of doing this kind of thing, you can rely on the modules having dependencies on each other, and then System will download and execute the first module and also all of its dependencies:

```js
// The module at url1 has a dependency on url2's module, and systemjs will download and execute both of them
System.import(url)
```

**Comment by pchainho** [comment] 2019-06-12 21:46
In my case, the modules to be imported are only known during runtime according to input provided by the user, and they are independent, ie there are no direct dependencies on each other.

However, the asynchronous functions importing these modules are the ones having a dependency on each other:

Promise A imports mod1
Promise B imports mod2
Promise B is called when Promise A is resolved

Anyway, your first example also does not work and is very similar to how I'm testing SystemJS. The exported function from the second imported module is not available .

**Comment by joeldenning** [comment] 2019-06-13 00:24
I just created https://github.com/joeldenning/system-import-chaining which shows that the first example from above works. Here's a gif of it working:

![promise-chaining](https://user-images.githubusercontent.com/5524384/59394789-bc422c00-8d89-11e9-8236-ce3d1762880b.gif)

If the first example I posted doesn't work for you, could you push a minimal repo that reproduces the issue and link to it here? Looking at your code from above, again, I think that the most likely problem is with your code and a couple weird things with it:

1) You should use promise chaining. There's no need to call `new Promise()` or `resolve()` when you can create a promise with `System.import()` and chain it by returning a promise from inside of `.then()`. 
2) `var instance = new result.default();` is likely the source of  your problems. I don't know you're doing that, but if you want your promise to resolve with the module then you should not do that. The log statement later on in the code seems to indicate that you're hoping that the return value of `new result.default()` will be a module. But that is not true at all. Don't know where that code snippet is coming from

I'm closing this because it doesn't appear that there is a bug with SystemJS here. If you're able to create the repo that reproduces the problem, or if you find out something else relevant that is causing the issue, feel free to comment further and/or reopen

**Closed by joeldenning** 2019-06-13 00:24 UTC

**Comment by pchainho** [comment] 2019-06-14 16:29
thanks a lots @joeldenning  

from the documentation I understood ES6 `import` / `export` would work fine but looking into your code I see we need `System.register()`. I'm now using @babel/plugin-transform-modules-systemjs and it works fine
