### ISSUE TITLE
Failed to import plugin module Error: Unable to resolve specifier

### ISSUE THREAD

**Issue by stevenvachon** [systemjs/systemjs#2152] opened 2020-04-02 15:45 UTC
main.js:
```js
import React from 'react';
System.set('react', React);
System.import('./async-module.js');
```

async-module.js (compiled):
```js
define(['react'], () => {});
```

produces:
```
Failed to import plugin module Error: Unable to resolve specifier 'react' from http://localhost/async-module.js
    at system.js:533
    at m.b.resolve (system.js:529)
    at system.js:329
    at Array.map (<anonymous>)
    at system.js:327
```

---

I'm confused.

**Comment by joeldenning** [comment] 2020-04-02 16:12
Hi @stevenvachon - good question, this behavior can be confusing but I'll explain what's happening.

Modules in SystemJS registry should be identified with a full URL, but `System.set(id)` allows you to insert modules that aren't a full URL.

Another way of explaining this - when loading modules via System.import(), SystemJS calls `System.resolve(id)`, which turns the id into a full URL. It then searches the module registry for that full URL.

When you call `System.set('react', React)`, you're inserting a module into the registry that is not identified by a URL, which means it won't be importable by System.import() or `define(['react'])`

The solution is to do the following:
```js
System.set(System.resolve('react'), React);
```

Note that doing so might result in an error, if `react` is not in your import map. So you would need to put react into the import map before calling that.

^ All of of this behavior is a result of trying to follow browser specs, which only allow for full URLs in the module registry. I concede that it's rather confusing, and think we could do a couple things to fix it:

1. Throw an error inside of System.set(id) if the id is not a URL.
2. Alter System.resolve() to check the module registry for bare specifiers. This one is more controversial and I don't think we'd want to do it.

**Comment by stevenvachon** [comment] 2020-04-02 16:40
Thanks! That worked for my `React` example. It fails differently for a module with a namespace ([@grafana/data](https://npmjs.com/@grafana/data)), though:
```
Uncaught Error: Unable to resolve specifier '@grafana/data' from http://localhost/
    at system.js:533
    at m.b.resolve (system.js:529)
    at Xs (plugin_loader.ts:67)
    at Object.Vw/f (plugin_loader.ts:70)
    at i (bootstrap:84)
    at Module.zl43 (app.c141149e3bdedc71b3bc.js:2)
    at i (bootstrap:84)
    at t (bootstrap:45)
    at Array.r [as push] (bootstrap:32)
    at vendors~app.c141149e3bdedc71b3bc.js:2
```

**Comment by guybedford** [comment] 2020-04-02 16:58
> Throw an error inside of System.set(id) if the id is not a URL.

@joeldenning good point - how about we make it a development-time-only warning?

> Alter System.resolve() to check the module registry for bare specifiers. This one is more controversial and I don't think we'd want to do it.

I already regret doing this in the AMD system so would prefer to avoid.

**Comment by joeldenning** [comment] 2020-04-02 17:33
> I have no import map, but why would I need one if I'm pointing to existing modules (runtime objects)?

System.set is a SystemJS-specific feature that is not part of any browser spec. SystemJS provides polyfill-like behavior for module specs that will be implemented by browsers, and there is no current spec for loading a module without a URL and network request.

Since browser module loading specs are currently trending towards only URL-based loading, that is the direction we've gone with systemjs, as well. Like Guy Bedford said above, we allowed for this with the named-register AMD system, and it has been a huge pain to maintain and integrate into the URL-based module registry.

> how about we make it a development-time-only warning?

Sure - I'll add this to #2151 

I am closing this issue since it is expected behavior. Feel free to comment further or reopen.

**Closed by joeldenning** 2020-04-02 17:33 UTC

**Comment by stevenvachon** [comment] 2020-04-06 16:40
Shouldn't  `System.resolve('@namespace/name')` be supported, though? It currently throws an error.

**Comment by stevenvachon** [comment] 2020-04-06 19:16
I'm still getting the same error, and I now have an import map:
```js
import _ from 'lodash';

const exposeToPlugin = modules => {
  const script = document.createElement('script');
  script.type = 'importmap';
  script.textContent = JSON.stringify({
    imports: Object.fromEntries(modules.map(([key]) => [key, 'irrelevant-filename.js']))
  });
  document.currentScript.after(script);

  modules.forEach(([key, value]) => System.set(System.resolve(key), value));
};

exposeToPlugin([
  ['lodash', _]
]);
```

**Comment by joeldenning** [comment] 2020-04-06 19:37
Is your import map being installed before any SystemJS modules are loaded? Import maps must be added to the DOM before the first SystemJS module is loaded. This is per [this part of the import maps](https://github.com/WICG/import-maps#installation):

> Because they affect all imports, any import maps must be present and successfully fetched before any module resolution is done.

Also iss the error about lodash now? If the error is still about react, the explanation might be that you need to add `react` to the `exposeToPlugin()` call

**Comment by stevenvachon** [comment] 2020-04-06 19:40
> Is your import map being installed before any SystemJS modules are loaded?

Yes

> Also is the error about lodash now? If the error is still about react, the explanation might be that you need to add `react` to the `exposeToPlugin()` call

Lodash

**Comment by joeldenning** [comment] 2020-04-06 19:46
In that case, it's hard to diagnose this without a code example demonstrating the issue. Can you create a code sandbox, using the template below? Feel free to modify to use your `exposeToPlugin` function

https://codesandbox.io/s/quirky-antonelli-2kusz?file=/index.html

**Comment by stevenvachon** [comment] 2020-04-07 14:23
Sure thing: https://repl.it/@StevenVachon1/SystemJSImportMap

**Comment by joeldenning** [comment] 2020-04-07 15:55
Here's a fork of your repl.it that works - https://repl.it/repls/VividButteryInterfacestandard. Here are the changes I made:

1. I called and waited for [`System.prepareImport()`](https://github.com/systemjs/systemjs/blob/master/docs/hooks.md) before calling `System.resolve()`. This is necessary, since you cannot call System.resolve() until the import map has been processed. Normally, you don't have to call System.prepareImport() manually, since it's called as part of System.import(). But in this case, you're wanting to call System.resolve() before the first import.
2. I changed the import map ScriptElement to be have `<script type="systemjs-importmap">`, instead of `type="importmap"`. This is necessary to distinguish between import maps processed by systemjs and those processed by the browser, and is [documented here](https://github.com/systemjs/systemjs/blob/master/docs/import-maps.md#loading-import-maps)
3. I changed `System.import('plugin.js')` to `System.import('./plugin.js')`, and changed `'irrelevant-filename.js'` to `./irrelevant-filename.js'`. This is because the import map spec requires page-relative URLs to start with `./` or `/`. You can read more [in this part of the spec](https://wicg.github.io/import-maps/#parse-a-url-like-import-specifier)

**Comment by stevenvachon** [comment] 2020-04-07 17:48
Thanks!!

**Comment by stevenvachon** [comment] 2020-04-07 19:01
For anyone who comes across this in the future, be sure not to use the same file name for each `System.set()` module, as "irrelevant" as it may be, as to avoid overwriting previous entries when setting multiple. I did this:
```js
`./${key}/irrelevant-filename.js`
```
