### ISSUE TITLE
CommonJS module is empty object while loaded with `System.import` in node

### ISSUE THREAD

**Issue by dmatteo** [systemjs/systemjs#823] opened 2015-10-06 09:42 UTC
When I try to load a CommonJS module using `System.import` in Node (v0.10), all I get is an empty object.

This assertion fails
```javascript
it('should load a cjs module loaded with a plugin', function () {
  return System.import('components/SimpleComponent/SimpleComponent').then(function (component) {
    return expect(component, 'to be a function');
  })
});
```

While this works as expected
```javascript
it('should load a cjs module loaded with node require', function () {
  var SimpleComponent = require('../app/components/SimpleComponent/SimpleComponent');
  expect(SimpleComponent, 'to be a function');
});
```

I have also created a repo to easily reproduce the issue:
https://github.com/dmatteo/systemjs-issue-cjs

**Comment by dmatteo** [comment] 2015-10-06 09:44
```
  "devDependencies": {
    "babel": "5.8.23",
    "jsdomify": "^0.6.1",
    "jspm": "^0.16.11",
    "mocha": "^2.3.3",
    "react": "0.13.3",
    "systemjs": "^0.19.3",
    "unexpected": "^9.16.1"
  },
```
`jsdom 3.x` loaded by `jsdomify`

**Comment by guybedford** [comment] 2015-10-06 12:16
Closing as a duplicate of https://github.com/systemjs/systemjs/issues/821. If it turns out I'm mistaken we can certainly reopen.

**Closed by guybedford** 2015-10-06 12:16 UTC
