### ISSUE TITLE
Incorrect module ID mapping

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#462] opened 2015-05-21 16:12 UTC
```
import tmplMain from './text/main.html!text'
```

ends up resolving as

```
github:systemjs/plugin-text@0.0.2/main.html!github:systemjs/plugin-text@0.0.2
```

Is this a bug?

**Comment by guybedford** [comment] 2015-05-21 20:14
Yes this is by design unfortunately. It is being resolved in the new normalization function coming in the next release.

**Comment by matthewp** [comment] 2015-05-21 23:14
Seems like something that should wait for 1.0

**Comment by matthewp** [comment] 2015-05-21 23:15
Oops, didn't read close enough

**Comment by guybedford** [comment] 2015-06-05 12:47
This should now be working with the latest SystemJS. Let me know if you still have issues at all.

**Closed by guybedford** 2015-06-05 12:47 UTC

**Comment by mbaneryd** [comment] 2016-05-12 11:59
Hi,
I'm trying to use system.js to load a Dojo application instead of using the built in dojo loader.
And I'm running into the same problem (using version 0.19.27), that the plugin arguments gets normalized. The "dojo/has" plugin does not like that at all.

But this seems to be intentional, as you said above, and not fixed in the latest version. Are you still planning on changing this in 1.0?

https://github.com/systemjs/systemjs/blob/master/lib/plugins.js#L82

**Comment by rhpijnacker** [comment] 2017-07-15 21:30
@guybedford, @mbaneryd: Hi, I am also trying to see whether we can use system.js to load an existing Dojo application (so we can also load Angular alongside it). Could you share some insights you might have on the chances of getting anything like "dojo/has" working with system.js?

**Comment by guybedford** [comment] 2017-07-18 17:57
@rhpijnacker dojo/has is probably best substituted by the conditional system in SystemJS. This is a configuration-based mapping based on condition modules evaluating to true or false. Perhaps look at the jspm 0.17 beta guide conditional sections to get a feel for this.
