### ISSUE TITLE
Windows - Firefox: Error evaluating <fileName>.ts

### ISSUE THREAD

**Issue by andre-kaufmann** [systemjs/systemjs#1242] opened 2016-04-28 14:54 UTC
We have a problem only under Windows with Firefox. We can't reproduce it with other browser. Other files are loaded and properly evaluated. We can see that the tooltip.ts file is also loaded (access via url works) but it gives us this error message as soon as SystemJS will evaluate it. We use Angular 1.5 and Typescript 1.8.10 if that helps.

```javascript
Error: 
Evaluating http://localhost:8080/app/components/tooltip/tooltip.ts
Error loading http://localhost:8080/app/components/tooltip/tooltip.ts as "../../components/tooltip/tooltip" from http://localhost:8080/app/modules/etf/index.ts
  system.js (Line 59)
```

**Environment:**
Windows 7 (64bit)
Firefox 39
Angular 1.5
Typescript 1.8.10
SystemJS 0.19.25

**Comment by guybedford** [comment] 2016-04-28 15:22
Have you tried debugging the execution in `http://localhost:8080/app/components/tooltip/tooltip.ts` here?

**Comment by andre-kaufmann** [comment] 2016-04-29 09:55
We have found the issue. The reason was that we had a function declaration inside an if-statement in "strict mode". Firefox (<= v45) and Safari fail. This is the error message with the transpiled tooltip.js file without SystemJS:

`SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function` 

It would be much better if SystemJS don't hide/swallow this error message.

**Comment by guybedford** [comment] 2016-04-29 11:54
Ok this sounds like a duplicate of https://github.com/systemjs/systemjs/issues/1241 then.

You should be able to get the original error by inspecting `e.originalErr` from the catch handler. But if not let me know as well.

**Closed by guybedford** 2016-04-29 11:54 UTC

**Comment by npbenjohnson** [comment] 2016-05-01 05:07
This isn't exactly the same as #1241, FF doesn't throw an error in that case so it never hits the catch handler.
