### ISSUE TITLE
'require(...)' calls erroneously parsed even within strings in CommonJS

### ISSUE THREAD

**Issue by theefer** [systemjs/systemjs#311] opened 2015-01-11 17:34 UTC
Trying to load file containing the following code will fail:

``` javascript
// bug.js
"format cjs";

var x = " require('fail')";

// Note that the following is OK:
// var y = "require('fail')";
```

will fail with the following error:

```
err  Error: Error loading "fail" at file:/home/seb/.../fail.js
     Error loading "fail" from "2-async/bug" at file:/home/seb/.../bug.js
     ENOENT, open '/home/seb/.../fail.js'
```

It would seem that the [CommonJS parsing regex](https://github.com/systemjs/systemjs/blob/master/lib/extension-cjs.js#L10) doesn't distinguish `require` calls from `require` occurrences within a string.

This was experience in the wild with the `keygrip` library ([offending code](https://github.com/crypto-utils/keygrip/blob/1.0.1/index.js#L37)) when trying to load the `twitter` node library (see https://github.com/jspm/registry/pull/104).

**Comment by theefer** [comment] 2015-01-11 17:36
I could try and extend the regex to cater for this situation, although I'm slightly worried that these regexes are getting increasingly unreadable. Will there be a point when we need to fallback to richer parsing (esprima etc), or was that deemed to costly? I guess it'd be fine offline, but perhaps more contentious when done in the browser?

**Comment by theefer** [comment] 2015-01-11 20:23
I also can't seem to understand the magic that prevents the loader from parsing requires from comments, e.g.

```
// var x = require('fail');
```

**Comment by theefer** [comment] 2015-01-11 20:30
Scrap the last comment, I found the code to strip commented lines.

**Comment by theefer** [comment] 2015-01-11 23:03
See https://github.com/systemjs/systemjs/pull/312 for a candidate fix.

**Comment by guybedford** [comment] 2015-01-19 18:40
New fix would be to refactor this detection to use simple tokenizing as in https://github.com/systemjs/systemjs/blob/5f460116abcc25cad96373ccd186db71e5db735a/loader.js#L49, or even use Traceur itself.

**Comment by guybedford** [comment] 2015-01-23 01:19
From https://github.com/systemjs/systemjs/pull/326 it looks like this is a "wontfix" for now... Sorry!

**Comment by theefer** [comment] 2015-01-23 01:43
Given that it does actually break real usage in the wild, the bug should probably remain open?

I encountered this while preparing a live demo for a talk and trying to use the twitter npm module. So the workaround would be either to find another alternative twitter client (`twitter` seemed the most appropriate), or not using jspm :-(

I appreciate this may require a more involved fix, but I just want to make it clear that it's not just an academic and hypothetical issue, sadly.

**Comment by guybedford** [comment] 2015-01-23 09:44
@theefer are you referring to `jspm install npm:twitter`? Is this designed to work in the browser?

**Comment by theefer** [comment] 2015-01-23 09:49
I was running this particular code off Node (jspm run), but I was hoping that it could also be used in the browser. That said, I'd realised it must rely on the httpmodule from Node, so it might not work anyway, unless it can somehow be automatically translated to AJAX requests? 

Curious what browserify does in this case, is it supported?

**Comment by guybedford** [comment] 2015-01-23 10:02
@theefer right thanks I see exactly what you mean. When I fix it, I end up getting a hanging issue unfortunately - were you getting this or is it a regression?

Browserify does provide an HTTP module, which is supported in jspm.

**Comment by guybedford** [comment] 2015-01-23 10:03
@theefer right thanks I see exactly what you mean. When I fix it, I end up getting a hanging issue unfortunately - were you getting this or is it a regression?

Browserify does provide an HTTP module, which is supported in jspm.

**Comment by theefer** [comment] 2015-01-23 14:21
Do you mean the twitter module specifically? It worked for me but I only tried it in Node via jspm run, not in the browser.

**Comment by guybedford** [comment] 2015-01-23 14:22
@theefer yes the twitter module - I tried with `jspm run` on jspm master and it got stuck in a loop. Hope it's not a regresion on master, but if so I'll have to look into it.

To update on this issue again from #326, the question is whether to accept a 4x performance degradation for CommonJS require extraction and have this support, or to mark as a wont-fix. I'm completely on the fence here still. Having perfect regex detection is so important to the project that I'm almost willing to take the hit, but it needs to be justified.

**Comment by theefer** [comment] 2015-01-23 14:22
To be specific: I only tried it (successfully) with my fix (string regexing), I didn't try https://github.com/systemjs/systemjs/pull/326. Do you need me to?

**Comment by guybedford** [comment] 2015-01-23 14:22
I also tried that with SystemJS too, I don't think it's that.

**Comment by guybedford** [comment] 2015-01-26 10:10
@theefer I think the best solution for this is actually https://github.com/crypto-utils/keygrip/pull/19. Let me know if that works for you.

**Comment by theefer** [comment] 2015-01-26 12:08
Seems like it would work (can't think of an easy way to test the fix until this is merged). Thanks!

The error that occurs when such bug is encountered is unexpected, but kind of helpful enough to track down the problem, so maybe it can be a "workaround it please" for now..?

**Comment by guybedford** [comment] 2015-01-27 11:02
Sure, as mentioned in https://github.com/systemjs/systemjs/pull/326#issuecomment-71628061 let's take this route for now, we can always come back to it later.

**Closed by guybedford** 2015-01-27 11:02 UTC

**Comment by theefer** [comment] 2015-01-27 12:57
Let's hope they accept your PR though otherwise this workaround won't work :-)

**Comment by guybedford** [comment] 2015-01-27 12:59
@theefer another workaround would be to add a map into the package.json override:

```json
{
  "map": {
    "keygrip": "@empty"
  }
}
```

**Comment by guybedford** [comment] 2015-01-27 20:31
@theefer I added this override in https://github.com/jspm/registry/blob/master/package-overrides/npm/keygrip%401.0.1.json and it should be working now.

**Comment by theefer** [comment] 2015-01-27 21:05
Given how niche that problem is, that seems like a decent workaround. Thanks for tracking and fixing this!
